const $=id=>document.getElementById(id), TYPES=[['all','Tümü'],['stock','Hisse'],['etf','ETF'],['crypto','Kripto'],['fund','Fon'],['index','Endeks'],['fx','Döviz'],['commodity','Emtia']];
const STORE='mic_mobile_github_v1'; let state={profile:null,portfolio:[],lastDecision:null,lastAsset:null,settings:{alphaKey:'',avSymbols:{},historyCache:{}}}; try{state={...state,...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{};state.settings={alphaKey:'',avSymbols:{},historyCache:{},...(state.settings||{})};
let market={updated_at:null,assets:[],fx:{USDTRY:40}},selected=null,activeType='all',chartPeriod='1A';
function save(){localStorage.setItem(STORE,JSON.stringify(state));renderHome();renderPortfolio()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function num(n,d=2){return Number(n||0).toLocaleString('tr-TR',{maximumFractionDigits:d})} function money(n,c='TRY'){return new Intl.NumberFormat('tr-TR',{style:'currency',currency:c,maximumFractionDigits:2}).format(n||0)}
function toast(t){$('toast').textContent=t;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2600)}
function nav(v){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===v));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='chart')drawLastChart()}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>nav(b.dataset.view));
function profileComplete(){const p=state.profile;return !!(p&&p.objective&&p.horizon&&p.risk&&p.maxPosition&&p.rebalanceBand)}
function renderHome(){$('homeProfile').textContent=profileComplete()?'Tamam':'Eksik';$('homeProfile').className=profileComplete()?'positive':'negative';$('homePortfolio').textContent=state.portfolio.length+' varlık';$('lastDecision').innerHTML=state.lastDecision?`<div class="decisionTitle">${esc(state.lastDecision.action)}</div><div class="hint">${esc(state.lastDecision.symbol)} · ${esc(state.lastDecision.summary)}</div>`:'Henüz analiz yapılmadı.'}
function renderChips(){$('chips').innerHTML=TYPES.map(([k,l])=>`<button class="chip ${activeType===k?'active':''}" data-type="${k}">${l}</button>`).join('')}
$('chips').onclick=e=>{const b=e.target.closest('[data-type]');if(!b)return;activeType=b.dataset.type;renderChips();runSearch()};renderChips();
async function loadMarket(){try{const r=await fetch('data/market.json?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);market=await r.json();$('dataStatus').textContent='SON VERİ';$('dataStatus').className='pill';const d=market.updated_at?new Date(market.updated_at):null;$('feedTime').textContent=d?'Güncelleme: '+d.toLocaleString('tr-TR'):'Veri zamanı yok';$('settingsStatus').textContent=`${market.assets.length} varlık yüklendi.`;runSearch();renderPortfolio();return true}catch(e){$('dataStatus').textContent='VERİ HATASI';$('dataStatus').className='pill warn';$('settingsStatus').textContent='Veri alınamadı: '+e.message;return false}}
$('refreshData').onclick=async()=>{const ok=await loadMarket();toast(ok?'Veri yenilendi':'Veri yenilenemedi')};
function norm(s){return String(s||'').toLocaleUpperCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function matchesType(a){return activeType==='all'||a.type===activeType}
function runSearch(){const q=$('searchInput').value.trim(),box=$('results');if(q.length<3){box.classList.add('hidden');return}const n=norm(q);const items=(market.assets||[]).filter(a=>matchesType(a)&&norm(a.symbol+' '+a.name).includes(n)).slice(0,30);box._items=items;box.innerHTML=items.length?items.map((a,i)=>`<div class="result" data-i="${i}"><strong>${esc(a.symbol)} — ${esc(a.name)}</strong><small>${label(a.type)} · ${esc(a.exchange||'')} · ${esc(a.currency||'')}</small></div>`).join(''):'<div class="result muted">Eşleşen varlık bulunamadı.</div>';box.classList.remove('hidden')}
$('searchInput').addEventListener('input',runSearch);$('results').onclick=e=>{const r=e.target.closest('[data-i]');if(!r)return;selected=$('results')._items[+r.dataset.i];$('results').classList.add('hidden');$('searchInput').value=selected.symbol+' — '+selected.name;renderSelected()};
function label(t){return ({stock:'Hisse',etf:'ETF',crypto:'Kripto',fund:'Fon',index:'Endeks',fx:'Döviz',commodity:'Emtia'})[t]||t}
function renderSelected(){$('selectedCard').classList.remove('hidden');$('selectedCard').innerHTML=`<div class="assetTop"><div><div class="symbol">${esc(selected.symbol)}</div><div class="assetName">${esc(selected.name)}</div></div><span class="badge">${label(selected.type)}</span></div><div class="hint">${esc(selected.exchange||'')} · ${esc(selected.currency||'')} · Son fiyat ${selected.price!=null?money(selected.price,selected.currency):'yok'}</div><div class="actions"><button id="analyze" class="primary">Analiz et</button><button id="openChart" class="ghost">Grafiği aç</button><button id="addPort" class="ghost wide">Portföye ekle</button></div>`;$('analysisPanel').classList.add('hidden');$('analyze').onclick=()=>analyzeAsset(selected);$('openChart').onclick=()=>openChart(selected);$('addPort').onclick=()=>addPortfolio(selected)}
