
function present(v){return v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v))}
function scoreAsset(a){let business=15,growth=10,valuation=8,technical=5,risk=8,known=0;if(present(a.roe)){business=Math.max(3,Math.min(30,15+(+a.roe-10)*.5));known++}if(present(a.revenue_growth)){growth=Math.max(2,Math.min(20,10+(+a.revenue_growth)*.35));known++}if(present(a.pe)){valuation=Math.max(2,Math.min(15,16-(+a.pe)*.35));known++}if(present(a.change)){technical=Math.max(1,Math.min(10,5+(+a.change)*.25));known++}if(present(a.volatility)){risk=Math.max(2,Math.min(15,15-(+a.volatility)*.2));known++}const macro=6,total=Math.round(business+growth+valuation+technical+macro+risk);return {business:Math.round(business),growth:Math.round(growth),valuation:Math.round(valuation),technical:Math.round(technical),macro,risk:Math.round(risk),score:Math.max(0,Math.min(100,total)),confidence:Math.min(95,35+known*12)}}
function fxRate(c){if(c==='TRY')return 1;if(c==='USD')return +market.fx?.USDTRY||40;if(c==='EUR')return +market.fx?.EURTRY||44;return 1}
function portfolioStats(){const rows=state.portfolio.map(p=>{const a=market.assets.find(x=>x.symbol===p.symbol&&x.type===p.type)||p;const price=+a.price||+p.currentPrice||+p.avgCost||0;const valueTRY=price*(+p.quantity||0)*fxRate(a.currency||p.currency);return {...p,...a,price,valueTRY}});const total=rows.reduce((s,x)=>s+x.valueTRY,0);rows.forEach(x=>x.weight=total?x.valueTRY/total*100:0);return {rows,total}}
function profileCap(a){const p=state.profile;let cap=+p.maxPosition;const riskCap=p.risk==='low'?6:p.risk==='medium'?10:15;cap=Math.min(cap,riskCap);if(a.type==='crypto')cap=Math.min(cap,p.risk==='high'?8:3);if(p.objective==='preserve')cap=Math.min(cap,5);if(p.objective==='speculative'&&p.risk==='high')cap=Math.max(cap,12);return cap}
function decision(a,s){if(!profileComplete())return {action:'PROFİL GEREKLİ',summary:'Karar üretmeden önce amaç, ufuk ve risk profili tamamlanmalıdır.',details:['Profil olmadan miktar önerisi yapılmaz.'],cls:'warn'};const ps=portfolioStats(),held=ps.rows.find(x=>x.symbol===a.symbol&&x.type===a.type),weight=held?.weight||0,cap=profileCap(a),band=+state.profile.rebalanceBand,details=[`MIC puanı ${s.score}/100; veri güveni %${s.confidence}.`,`Profil azami pozisyon limiti %${num(cap)}; tolerans ±%${num(band)}.`];if(held&&weight>cap+band){const targetValue=ps.total*cap/100,reduceTRY=Math.max(0,held.valueTRY-targetValue),unitTRY=held.price*fxRate(held.currency),sellQty=unitTRY>0?Math.min(held.quantity,Math.ceil(reduceTRY/unitTRY)):0;details.push(`Mevcut ağırlık %${num(weight)}; limit+tolerans %${num(cap+band)}.`);details.push(`${num(sellQty,6)} adet/lot sat, ${num(held.quantity-sellQty,6)} adet/lot tut; yaklaşık ${money(sellQty*unitTRY,'TRY')} azalt.`);return {action:'AZALT',summary:`${num(sellQty,6)} adet/lot azalt`,details,cls:'warn'}}
if(held&&s.score<45){details.push('Puan 45 altı; pozisyon tez ve veri kalitesi açısından yeniden incelenmelidir.');return {action:'SAT / TEZİ YENİLE',summary:`Azami ${num(held.quantity,6)} adet/lot`,details,cls:'bad'}}
if(held){details.push(`Ağırlık %${num(weight)} ve profil bandı içinde.`);return {action:'TUT',summary:'Mevcut miktarı koru',details,cls:''}}
if(s.score>=75){const budget=Math.min(+state.profile.monthlyContribution||0,portfolioStats().total*cap/100||+state.profile.monthlyContribution||0);const qty=a.price?Math.floor((budget/fxRate(a.currency))/a.price):0;details.push(budget>0?`Aylık katkı ve limit içinde yaklaşık ${num(qty,6)} adet/lot düşünülebilir.`:'Miktar için aylık yatırım tutarını profile gir.');return {action:'ADAY / KADEMELİ EKLE',summary:qty>0?`${num(qty,6)} adet/lot üst sınır`:'Miktar hesaplanamadı',details,cls:''}}
return {action:'İZLE',summary:'Yeni pozisyon açma',details,cls:'warn'}}
function analyzeAsset(a){const s=scoreAsset(a),d=decision(a,s);state.lastDecision={action:d.action,symbol:a.symbol,summary:d.summary};state.lastAsset=a;save();$('analysisPanel').classList.remove('hidden');$('analysisPanel').innerHTML=`<div class="assetTop"><div><div class="symbol">${a.price!=null?money(a.price,a.currency):'Fiyat yok'}</div><div class="assetName">Günlük değişim <span class="${(+a.change||0)>=0?'positive':'negative'}">${present(a.change)?num(a.change):'—'}%</span></div></div><span class="badge">MIC ${s.score}/100</span></div><div class="analysis"><div class="cell"><span>Güven</span><strong>%${s.confidence}</strong></div><div class="cell"><span>İş kalitesi</span><strong>${s.business}/30</strong></div><div class="cell"><span>Büyüme</span><strong>${s.growth}/20</strong></div><div class="cell"><span>Değerleme</span><strong>${s.valuation}/15</strong></div><div class="cell"><span>Teknik</span><strong>${s.technical}/10</strong></div><div class="cell"><span>Risk kalitesi</span><strong>${s.risk}/15</strong></div></div><div class="decision ${d.cls||''}"><div class="decisionTitle">${esc(d.action)}</div><div>${esc(d.summary)}</div><ul class="reason">${d.details.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`}
function addPortfolio(a){if(state.portfolio.some(x=>x.symbol===a.symbol&&x.type===a.type))return toast('Bu varlık portföyde mevcut');const q=prompt(a.symbol+' adet/lot:','10');if(q===null||!(+q>0))return;const c=prompt('Ortalama maliyet ('+(a.currency||'TRY')+'): ',String(a.price||0));if(c===null)return;state.portfolio.push({symbol:a.symbol,name:a.name,type:a.type,exchange:a.exchange,currency:a.currency,quantity:+q,avgCost:+c||0,currentPrice:+a.price||+c||0});save();toast('Portföye eklendi');nav('portfolio')}
function renderPortfolio(){const ps=portfolioStats();$('totalValue').textContent=money(ps.total,'TRY');$('positionCount').textContent=ps.rows.length;const box=$('portfolioList');if(!ps.rows.length){box.innerHTML='<div class="card empty">Portföy boş. Araştırma ekranından varlık ekle.</div>';return}box.innerHTML=ps.rows.map((p,i)=>{const pnl=(p.price-p.avgCost)*p.quantity*fxRate(p.currency);const s=scoreAsset(p),d=decision(p,s);return `<div class="portfolioItem"><div class="assetTop"><div><div class="symbol">${esc(p.symbol)}</div><div class="assetName">${esc(p.name)}</div></div><span class="badge">%${num(p.weight)}</span></div><div class="small"><div><span>Adet</span><strong>${num(p.quantity,6)}</strong></div><div><span>Fiyat</span><strong>${money(p.price,p.currency)}</strong></div><div><span>Açık K/Z</span><strong class="${pnl>=0?'positive':'negative'}">${money(pnl,'TRY')}</strong></div></div><div class="hint"><b>${esc(d.action)}</b> · ${esc(d.summary)}</div><div class="portfolioBtns"><button data-a="analyze" data-i="${i}">Analiz</button><button data-a="chart" data-i="${i}">Grafik</button><button data-a="delete" data-i="${i}">Sil</button></div></div>`}).join('')}
$('portfolioList').onclick=e=>{const b=e.target.closest('[data-a]');if(!b)return;const p=portfolioStats().rows[+b.dataset.i];if(b.dataset.a==='delete'){if(confirm(p.symbol+' silinsin mi?')){state.portfolio=state.portfolio.filter(x=>!(x.symbol===p.symbol&&x.type===p.type));save()}}else if(b.dataset.a==='chart')openChart(p);else{selected=p;nav('search');renderSelected();analyzeAsset(p)}}
$('samplePortfolio').onclick=()=>{state.portfolio=[{symbol:'FROTO',name:'Ford Otomotiv Sanayi A.Ş.',type:'stock',exchange:'BIST',currency:'TRY',quantity:1050,avgCost:40.78},{symbol:'TUPRS',name:'Tüpraş',type:'stock',exchange:'BIST',currency:'TRY',quantity:395,avgCost:63.32},{symbol:'LUNR',name:'Intuitive Machines, Inc.',type:'stock',exchange:'NASDAQ',currency:'USD',quantity:285.628571,avgCost:17.5}];save();toast('Örnek portföy yüklendi')}

const PERIOD_DAYS={'1H':5,'1A':22,'3A':66,'6A':132,'1Y':252}
function assetKey(a){return `${a.type||'asset'}:${a.symbol}`}
function renderPeriodButtons(){document.querySelectorAll('.period').forEach(b=>b.classList.toggle('active',b.dataset.period===chartPeriod))}
$('chartPeriods').onclick=e=>{const b=e.target.closest('[data-period]');if(!b)return;chartPeriod=b.dataset.period;renderPeriodButtons();drawLastChart()}
function filterHistory(hist,period){const rows=[...hist].filter(x=>present(x.close)).sort((a,b)=>String(a.date).localeCompare(String(b.date)));if(period==='YTD'){const y=new Date().getFullYear();return rows.filter(x=>new Date(x.date).getFullYear()===y)}const n=PERIOD_DAYS[period]||22;return rows.slice(-n)}
function openChart(a){state.lastAsset=a;save();nav('chart');drawLastChart()}
function cachedHistory(a){return state.settings.historyCache?.[assetKey(a)]?.history||[]}
function drawLastChart(){const a=state.lastAsset;renderPeriodButtons();if(!a){$('chartTitle').textContent='';$('chartMessage').textContent='Önce bir varlık seç.';$('chartMessage').classList.remove('hidden');clearCanvas();return}const live=market.assets.find(x=>x.symbol===a.symbol&&x.type===a.type)||a;const apiHist=cachedHistory(live),hist=apiHist.length?apiHist:(live.history||[]);$('chartTitle').textContent=live.symbol+' · '+live.name;const filtered=filterHistory(hist,chartPeriod);$('chartInfo').textContent=`${live.exchange||''} · ${live.currency||''} · ${chartPeriod} · ${filtered.length} veri noktası${apiHist.length?' · Alpha Vantage':''}`;if(filtered.length>=2){$('chartMessage').classList.add('hidden');drawLine(filtered);return}if(live.performance&&present(live.performance[chartPeriod])){$('chartMessage').classList.add('hidden');drawPerformance(live.performance,chartPeriod);return}$('chartMessage').textContent='Bu dönem için günlük fiyat geçmişi yok. Ayarlar bölümüne API anahtarı girip alttaki düğmeye bas.';$('chartMessage').classList.remove('hidden');clearCanvas()}
function drawPerformance(perf,period){const c=$('chartCanvas'),r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;const ctx=c.getContext('2d');ctx.scale(d,d);const W=r.width,H=r.height,v=+perf[period],max=Math.max(10,Math.abs(v)),zero=H*.62,bw=Math.min(170,W*.34),h=(H*.43)*(Math.abs(v)/max),x=(W-bw)/2,y=v>=0?zero-h:zero;ctx.clearRect(0,0,W,H);ctx.strokeStyle='#52647d';ctx.beginPath();ctx.moveTo(35,zero);ctx.lineTo(W-35,zero);ctx.stroke();ctx.fillStyle=v>=0?'#42d39a':'#ff6b78';ctx.fillRect(x,y,bw,h);ctx.fillStyle='#f5f8ff';ctx.textAlign='center';ctx.font='bold 22px system-ui';ctx.fillText((v>0?'+':'')+num(v)+'%',W/2,v>=0?Math.max(28,y-14):Math.min(H-45,y+h+30));ctx.fillStyle='#9cabc1';ctx.font='16px system-ui';ctx.fillText(period+' dönem getirisi',W/2,H-22);ctx.textAlign='left'}
function clearCanvas(){const c=$('chartCanvas'),ctx=c.getContext('2d'),r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;ctx.clearRect(0,0,c.width,c.height)}
function drawLine(hist){const c=$('chartCanvas'),r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;const ctx=c.getContext('2d');ctx.scale(d,d);const W=r.width,H=r.height,p=34,vals=hist.map(x=>+x.close),min=Math.min(...vals),max=Math.max(...vals),span=max-min||1;ctx.clearRect(0,0,W,H);ctx.strokeStyle='#263b59';ctx.lineWidth=1;for(let i=0;i<5;i++){const y=p+(H-2*p)*i/4;ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(W-p,y);ctx.stroke()}ctx.strokeStyle='#42d39a';ctx.lineWidth=2.3;ctx.beginPath();hist.forEach((x,i)=>{const xx=p+(W-2*p)*i/(hist.length-1),yy=p+(H-2*p)*(max-(+x.close))/span;i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy)});ctx.stroke();ctx.fillStyle='#9cabc1';ctx.font='11px system-ui';ctx.fillText(num(max),4,16);ctx.fillText(num(min),4,H-28);ctx.textAlign='center';ctx.fillText(String(hist[0].date).slice(5),p,H-9);ctx.fillText(String(hist.at(-1).date).slice(5),W-p,H-9);ctx.fillStyle='#f5f8ff';ctx.textAlign='left';ctx.font='bold 14px system-ui';ctx.fillText('Son: '+num(vals.at(-1)),p,22)}

function alphaKey(){return String(state.settings.alphaKey||'').trim()}
async function fetchJson(url,timeout=18000){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),timeout);try{const r=await fetch(url,{signal:ctl.signal,cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(timer)}}
async function alphaFetch(params){const key=alphaKey();if(!key)throw new Error('API anahtarı girilmedi');const q=new URLSearchParams({...params,apikey:key});const data=await fetchJson('https://www.alphavantage.co/query?'+q.toString());const msg=data['Error Message']||data.Note||data.Information;if(msg)throw new Error(msg);return data}
async function resolveAlphaSymbol(a){const cached=state.settings.avSymbols?.[assetKey(a)];if(cached)return cached;if(a.exchange!=='BIST'){state.settings.avSymbols[assetKey(a)]=a.symbol;save();return a.symbol}const data=await alphaFetch({function:'SYMBOL_SEARCH',keywords:a.symbol});const matches=data.bestMatches||[];const best=matches.find(m=>String(m['8. currency']||'').toUpperCase()==='TRY'||/turkey|istanbul/i.test(String(m['4. region']||'')))||matches[0];if(!best)throw new Error('Alpha Vantage bu BIST sembolünü bulamadı');const symbol=best['1. symbol'];state.settings.avSymbols[assetKey(a)]=symbol;save();return symbol}
async function fetchAlphaHistory(a){if(a.type==='crypto'){const data=await alphaFetch({function:'DIGITAL_CURRENCY_DAILY',symbol:a.symbol,market:'USD'});const key=Object.keys(data).find(k=>/Time Series/i.test(k));if(!key)throw new Error('Kripto günlük seri bulunamadı');const hist=Object.entries(data[key]).map(([date,row])=>({date,open:+(row['1a. open (USD)']||row['1. open']),high:+(row['2a. high (USD)']||row['2. high']),low:+(row['3a. low (USD)']||row['3. low']),close:+(row['4a. close (USD)']||row['4. close']),volume:+(row['5. volume']||0)})).filter(x=>present(x.close)).sort((x,y)=>x.date.localeCompare(y.date));if(hist.length<2)throw new Error('Yeterli kripto verisi gelmedi');state.settings.historyCache[assetKey(a)]={updatedAt:new Date().toISOString(),symbol:a.symbol,history:hist.slice(-370)};save();return hist}
const symbol=await resolveAlphaSymbol(a);const data=await alphaFetch({function:'TIME_SERIES_DAILY',symbol,outputsize:'compact'});const key=Object.keys(data).find(k=>/Time Series.*Daily/i.test(k));if(!key)throw new Error('Günlük fiyat serisi bulunamadı');const hist=Object.entries(data[key]).map(([date,row])=>({date,open:+row['1. open'],high:+row['2. high'],low:+row['3. low'],close:+row['4. close'],volume:+row['5. volume']})).filter(x=>present(x.close)).sort((x,y)=>x.date.localeCompare(y.date));if(hist.length<2)throw new Error('Yeterli günlük veri gelmedi');state.settings.historyCache[assetKey(a)]={updatedAt:new Date().toISOString(),symbol,history:hist.slice(-370)};save();return hist}
$('loadApiChart').onclick=async()=>{const a=state.lastAsset;if(!a)return toast('Önce varlık seç');if(!alphaKey()){nav('settings');toast('Önce Alpha Vantage API anahtarını gir');return}const b=$('loadApiChart'),old=b.textContent;b.disabled=true;b.textContent='API verisi alınıyor...';try{await fetchAlphaHistory(a);toast('Günlük grafik verisi alındı');drawLastChart()}catch(e){toast('API hatası: '+e.message);$('chartMessage').textContent='API hatası: '+e.message;$('chartMessage').classList.remove('hidden')}finally{b.disabled=false;b.textContent=old}}
$('saveApiKey').onclick=()=>{state.settings.alphaKey=$('alphaKey').value.trim();save();$('apiStatus').textContent=alphaKey()?'Anahtar bu cihazda kaydedildi.':'Anahtar silindi.';toast(alphaKey()?'API anahtarı kaydedildi':'API anahtarı silindi')}
$('testApiKey').onclick=async()=>{state.settings.alphaKey=$('alphaKey').value.trim();save();const b=$('testApiKey'),old=b.textContent;b.disabled=true;b.textContent='Test ediliyor...';try{const d=await alphaFetch({function:'SYMBOL_SEARCH',keywords:'IBM'});if(!(d.bestMatches||[]).length)throw new Error('Test sonucu boş');$('apiStatus').textContent='API bağlantısı başarılı.';toast('API bağlantısı başarılı')}catch(e){$('apiStatus').textContent='API testi başarısız: '+e.message;toast('API testi başarısız')}finally{b.disabled=false;b.textContent=old}}

$('saveProfile').onclick=()=>{const p={objective:$('objective').value,horizon:$('horizon').value,risk:$('risk').value,maxDrawdown:+$('maxDrawdown').value,maxPosition:+$('maxPosition').value,rebalanceBand:+$('rebalanceBand').value,monthlyContribution:+$('monthlyContribution').value};if(!p.objective||!p.horizon||!p.risk)return toast('Amaç, ufuk ve risk seçilmeli');state.profile=p;save();toast('Profil kaydedildi');nav('home')}
function loadProfileForm(){const p=state.profile;if(!p){$('objective').value='';$('horizon').value='';$('risk').value='';return}$('objective').value=p.objective;$('horizon').value=p.horizon;$('risk').value=p.risk;$('maxDrawdown').value=p.maxDrawdown;$('maxPosition').value=p.maxPosition;$('rebalanceBand').value=p.rebalanceBand;$('monthlyContribution').value=p.monthlyContribution||0}
$('clearData').onclick=()=>{if(confirm('Profil, portföy ve API anahtarı silinsin mi?')){localStorage.removeItem(STORE);state={profile:null,portfolio:[],lastDecision:null,lastAsset:null,settings:{alphaKey:'',avSymbols:{},historyCache:{}}};$('alphaKey').value='';$('apiStatus').textContent='';loadProfileForm();save();toast('Yerel veriler temizlendi')}}
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})
$('alphaKey').value=alphaKey();$('apiStatus').textContent=alphaKey()?'API anahtarı bu cihazda kayıtlı.':'API anahtarı girilmedi.';loadProfileForm();renderPeriodButtons();renderHome();renderPortfolio();loadMarket()
