(()=>{'use strict';
const $=id=>document.getElementById(id);const ui={q:$('q'),clear:$('clear'),results:$('results'),status:$('status'),selected:$('selected'),intent:$('intent'),answer:$('answer'),privacy:$('privacy'),loc:$('loc'),voice:$('voice'),net:$('net'),startTab:$('startTab'),rescueTab:$('rescueTab'),privacyTab:$('privacyTab'),toast:$('toast')};
const st={loc:null,sel:null,intent:'approach',timer:0,idx:0,mark:0,lastQuery:'',wide:null};
const labels={cafe:'Kafe',restaurant:'Restoran',bar:'Bar',pub:'Pub',fast_food:'Hızlı yemek',food_court:'Yemek alanı',nightclub:'Gece mekânı',beach:'Plaj',park:'Park / açık alan',hotel:'Otel',mall:'AVM / mağaza',shop:'Mağaza',beauty:'Kuaför / bakım',spa:'Spa / bakım',fitness:'Spor / fitness',health:'Sağlık',bank:'Banka / hizmet',office:'Ofis / işyeri',museum:'Müze',attraction:'Turistik yer',transport:'Ulaşım / bekleme alanı',city:'Şehir / bölge',unknown:'Tür bilinmiyor'};
const social=new Set(Object.keys(labels));const typeKeys=['cafe','restaurant','bar','pub','beauty','shop','beach','park','mall','transport'];const intents={approach:'Birine yaklaş',silence:'Sessizlik oldu',group:'Gruba katıl',question:'Bana soru sordu',end:'Kibarca bitir'};
const RINGS=[100,200,500];
const lex={
 bar:['bar','cocktail bar','wine bar','sports bar','lounge bar','xyz bar'],pub:['pub','tavern','biergarten','beer house','ale house'],cafe:['cafe','café','coffee','kahve','espresso','roastery','roaster','bakery cafe'],restaurant:['restaurant','restoran','ristorante','trattoria','bistro','diner','grill','kitchen','steakhouse','steak house','burger','pizza','sushi','noodle','bbq','shawarma','kebab','seafood','eatery','food'],fast_food:['fast food','takeaway','take away','drive thru','drive-thru'],food_court:['food court'],nightclub:['nightclub','night club','club','disco'],beach:['beach','plaj','pantai','shore','coast'],park:['park','garden','bahçe'],hotel:['hotel','resort','inn','suites','guest house','hostel'],mall:['mall','shopping centre','shopping center','plaza'],shop:['shop','store','mart','market','supermarket','hypermarket','grocery','7 eleven','7-eleven','eleven','minimarket'],beauty:['coiffure','kuafor','kuaför','salon','hair salon','barber','hairdresser','beauty','nail','nails','cosmetic','makeup','make up','lash','lashes','eyebrow'],spa:['spa','massage','wellness'],fitness:['gym','fitness','pilates','yoga','crossfit','sport'],health:['clinic','pharmacy','hospital','medical','dental','dentist','doctor'],bank:['bank','atm','exchange','money exchange'],office:['office','company','building','tower'],museum:['museum','galeri','gallery'],attraction:['attraction','viewpoint','monument'],transport:['station','bus station','metro','airport','ferry','terminal','taxi','parking']
};
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/\p{Diacritic}/gu,'').replace(/ı/g,'i').replace(/[^a-z0-9]+/g,' ').trim()}
function lev(a,b){a=norm(a);b=norm(b);if(!a||!b)return 99;const m=a.length,n=b.length,dp=Array(n+1).fill(0).map((_,i)=>i);for(let i=1;i<=m;i++){let prev=dp[0];dp[0]=i;for(let j=1;j<=n;j++){let tmp=dp[j];dp[j]=Math.min(dp[j]+1,dp[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=tmp}}return dp[n]}
function similar(a,b){a=norm(a);b=norm(b);if(a.length<3||b.length<3)return a===b;if(a.includes(b)||b.includes(a))return true;return lev(a,b)<=Math.max(1,Math.floor(Math.min(a.length,b.length)/4))}
function toast(s){ui.toast.textContent=s;ui.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>ui.toast.classList.remove('show'),2400)}
function status(s,k=''){ui.status.textContent=s;ui.status.className='status '+k}
function km(a,b,c,d){const R=6371,rad=x=>x*Math.PI/180,dl=rad(d-b),dp=rad(c-a),x=Math.sin(dp/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(dl/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function fetchJson(url,ms=12000){return new Promise((res,rej)=>{const c=new AbortController(),t=setTimeout(()=>{c.abort();rej(Error('timeout'))},ms);fetch(url,{signal:c.signal,headers:{accept:'application/json'}}).then(r=>{clearTimeout(t);if(!r.ok)throw Error('http');return r.json()}).then(res).catch(e=>{clearTimeout(t);rej(e)})})}
function sourceLabel(s){return s.includes('Yakın')?'Yakın harita verisi':'Açık harita verisi'}
function addr(o){const a=o.address||{},p=[a.road||a.pedestrian||a.neighbourhood||a.suburb||a.quarter,a.city||a.town||a.village||a.state,a.country].filter(Boolean);return p.length?p.join(', '):(o.display_name||'').split(',').slice(1,4).join(', ')}
function classify(o){const tags=o.tags||o.extratags||{},cls=norm(o.class),typ=norm(o.type),name=norm(o.name||o.display_name),vals=[tags.amenity,tags.shop,tags.tourism,tags.leisure,tags.natural,tags.office,tags.healthcare,tags.cuisine,tags.building,typ,cls].filter(Boolean).map(norm);const text=' '+[name,...vals].join(' ')+' ';
 const direct={bar:'bar',pub:'pub',cafe:'cafe',restaurant:'restaurant',fast_food:'fast_food',food_court:'food_court',nightclub:'nightclub',beach:'beach',park:'park',hotel:'hotel',mall:'mall',supermarket:'shop',convenience:'shop',department_store:'shop',shop:'shop',beauty:'beauty',hairdresser:'beauty',barber:'beauty',massage:'spa',spa:'spa',fitness_centre:'fitness',gym:'fitness',clinic:'health',pharmacy:'health',hospital:'health',bank:'bank',atm:'bank',office:'office',museum:'museum',attraction:'attraction',viewpoint:'attraction',station:'transport',bus_station:'transport',airport:'transport',ferry_terminal:'transport',city:'city',town:'city',village:'city',suburb:'city'};
 for(const v of vals){if(direct[v])return direct[v]}
 for(const [cat,words] of Object.entries(lex)){for(const w of words){const nw=norm(w);if(text.includes(' '+nw+' '))return cat}}
 const toks=name.split(' ').filter(x=>x.length>2);for(const [cat,words] of Object.entries(lex)){for(const token of toks){for(const w of words){if(similar(token,w))return cat}}}
 return 'unknown'}
function asPlace(o,source){const lat=+(o.lat||(o.center&&o.center.lat)),lon=+(o.lon||(o.center&&o.center.lon));const tags=o.tags||o.extratags||{};const name=o.name||tags.name||o.display_name?.split(',')[0]||'Sonuç';const p={id:source+':'+(o.osm_type||o.type||'')+':'+(o.osm_id||o.id||name+lat+lon),name,lat,lon,address:addr(o),source,type:classify({...o,tags,name}),raw:o};p.distance=st.loc&&lat&&lon?km(st.loc.lat,st.loc.lon,lat,lon):null;return p}
function score(p,q){let s=0,nq=norm(q),nn=norm(p.name);if(nn===nq)s+=500;if(nn.startsWith(nq))s+=300;if(nn.includes(nq))s+=180;if(p.type!=='unknown')s+=80;if(p.distance!=null)s+=Math.max(0,600-p.distance*100);return s}
function nameMatches(p,q){const nq=norm(q),nn=norm(p.name);if(nq.length<3)return false;if(nn.includes(nq)||nq.includes(nn))return true;return nn.split(' ').some(t=>similar(t,nq)||nq.split(' ').some(qt=>similar(t,qt)))}
function dedupe(a){const m=new Map();for(const p of a){if(!p.lat||!p.lon)continue;const k=norm(p.name)+'|'+Math.round(p.lat*2000)+'|'+Math.round(p.lon*2000);const old=m.get(k);if(!old||(p.distance??999)<(old.distance??999))m.set(k,p)}return [...m.values()]}
function render(list,msg){ui.results.innerHTML='';if(!list.length){status(msg||'Yakında uygun sonuç bulunamadı. 3 km’ye kadar genişletmeyi deneyin.','warn');return}status(msg||`${list.length} sonuç bulundu. Doğru mekânı seçin.`,'good');for(const p of list){const d=p.distance!=null?` • ${p.distance<1?Math.round(p.distance*1000)+' m':p.distance.toFixed(1)+' km'}`:'';const b=document.createElement('button');b.className='result';b.innerHTML=`<strong>${esc(p.name)}</strong><small>${esc(p.address||'Adres bilgisi yok')}${d}</small><span class="tag ${p.type==='unknown'?'warn':'good'}">${esc(labels[p.type]||labels.unknown)} · ${esc(sourceLabel(p.source))}</span>`;b.onclick=()=>select(p);ui.results.appendChild(b)}}
function expandButton(q){ui.results.innerHTML='';const b=document.createElement('button');b.className='result';b.innerHTML='<strong>500 m içinde eşleşme yok</strong><small>Yakındaki aramayı 3 km’ye kadar genişlet</small><span class="tag warn">Kontrollü genişletme</span>';b.onclick=()=>search(q,true);ui.results.appendChild(b);status('500 m içinde uygun sonuç bulunamadı. İsterseniz 3 km’ye kadar genişletin.','warn')}
async function overpass(q,r){if(!st.loc)return[];const reg=norm(q).split(' ').filter(Boolean).join('.*');const data=`[out:json][timeout:12];nwr(around:${r},${st.loc.lat},${st.loc.lon})["name"~"${reg}",i];out center tags 60;`;const j=await fetchJson('https://overpass-api.de/api/interpreter?data='+encodeURIComponent(data),14000);return (j.elements||[]).map(e=>asPlace({id:e.id,lat:e.lat,lon:e.lon,center:e.center,tags:e.tags||{},name:e.tags&&e.tags.name,type:e.type},'Yakın harita verisi'))}
async function nominatim(q,local){const vb=st.loc&&local?`&viewbox=${[st.loc.lon-.04,st.loc.lat+.04,st.loc.lon+.04,st.loc.lat-.04].join(',')}&bounded=0`:'';const url=`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=20&addressdetails=1&extratags=1&namedetails=1&dedupe=1&accept-language=tr,en${vb}&q=${encodeURIComponent(q)}`;const a=await fetchJson(url,12000);return a.map(x=>asPlace(x,'Açık harita verisi'))}
async function search(q,wide=false){q=q.trim();st.lastQuery=q;if(q.length<3){ui.results.innerHTML='';status('En az 3 harf yazın veya konumunuzu kullanın.');return}const mark=++st.mark;status(st.loc?'Yakın çevrede aranıyor…':'Açık veri aranıyor…');let arr=[];if(st.loc){for(const r of (wide?[3000]:RINGS)){try{const local=(await overpass(q,r)).filter(p=>nameMatches(p,q)&&p.distance!=null&&p.distance<=r/1000);if(local.length){arr=local.sort((a,b)=>a.distance-b.distance).slice(0,8);if(mark!==st.mark)return;render(arr,`${arr.length} yakın sonuç bulundu (${r<1000?r+' m':r/1000+' km'}). Doğru mekânı seçin.`);return}}catch(e){}}
 if(!wide){expandButton(q);return}
 try{arr=(await nominatim(q,true)).filter(p=>nameMatches(p,q)&&p.distance!=null&&p.distance<=3).sort((a,b)=>a.distance-b.distance).slice(0,8)}catch(e){arr=[]}if(mark!==st.mark)return;render(arr,arr.length?`${arr.length} sonuç bulundu (3 km içinde). Doğru mekânı seçin.`:'3 km içinde uygun açık veri sonucu bulunamadı.','warn');return}
 try{arr=(await nominatim(q,false)).filter(p=>nameMatches(p,q)).sort((a,b)=>score(b,q)-score(a,q)).slice(0,8)}catch(e){arr=[]}if(mark!==st.mark)return;render(arr,arr.length?`${arr.length} açık veri sonucu bulundu. Doğru mekânı seçin.`:'Açık veride uygun sonuç bulunamadı. Mekân adı + şehir yazın.','warn')}
async function nearby(){if(!st.loc)return;status('Yakındaki mekânlar aranıyor…');for(const r of [100,200,500]){try{const data=`[out:json][timeout:12];(nwr(around:${r},${st.loc.lat},${st.loc.lon})["name"]["amenity"];nwr(around:${r},${st.loc.lat},${st.loc.lon})["name"]["shop"];nwr(around:${r},${st.loc.lat},${st.loc.lon})["name"]["tourism"];nwr(around:${r},${st.loc.lat},${st.loc.lon})["name"]["leisure"];nwr(around:${r},${st.loc.lat},${st.loc.lon})["name"]["healthcare"];);out center tags 80;`;const j=await fetchJson('https://overpass-api.de/api/interpreter?data='+encodeURIComponent(data),14000);const arr=dedupe((j.elements||[]).map(e=>asPlace({id:e.id,lat:e.lat,lon:e.lon,center:e.center,tags:e.tags||{},name:e.tags&&e.tags.name,type:e.type},'Yakın harita verisi'))).filter(p=>p.distance!=null&&p.distance<=r/1000).sort((a,b)=>a.distance-b.distance).slice(0,10);if(arr.length){render(arr,`${arr.length} yakın mekân bulundu (${r} m). Doğru olanı seçin.`);return}}catch(e){}}status('500 m içinde açık veri mekânı bulunamadı. Mekân adını yazın; yakın çevrede arayacağım.','warn')}
function useLoc(){ui.loc.disabled=true;status('Konum izni bekleniyor…');navigator.geolocation.getCurrentPosition(pos=>{st.loc={lat:pos.coords.latitude,lon:pos.coords.longitude};ui.loc.disabled=false;status('Konum alındı. Yakındaki mekânlar aranıyor…','good');if(ui.q.value.trim().length>=3)search(ui.q.value.trim());else nearby()},e=>{ui.loc.disabled=false;status('Konum alınamadı. Android/Chrome konum iznini kontrol edin veya mekân adı + şehir yazın.','bad')},{enableHighAccuracy:true,timeout:12000,maximumAge:120000})}
function select(p){st.sel=p;st.idx=0;ui.selected.classList.remove('hidden');ui.intent.classList.remove('hidden');ui.answer.classList.remove('hidden');const trust=p.type==='unknown'?'Orta':'Yüksek';ui.selected.innerHTML=`<div class="selected"><div class="venue-title"><div><h2>${esc(p.name)}</h2><p>${esc(p.address||'Adres bilgisi yok')}</p></div><span class="badge ${trust==='Orta'?'medium':''}">Güven: ${trust}</span></div><div class="meta"><div>Tür <b>${esc(labels[p.type]||labels.unknown)}</b></div><div>Kaynak <b>${esc(sourceLabel(p.source))}</b></div>${p.distance!=null?`<div>Mesafe <b>${p.distance<1?Math.round(p.distance*1000)+' m':p.distance.toFixed(1)+' km'}</b></div>`:''}</div>${p.type==='unknown'?'<p>Tür net değilse tek dokunuşla düzeltin:</p>':''}<div class="chips">${typeKeys.map(t=>`<button class="pill ${p.type===t?'active':''}" data-type="${t}">${labels[t]}</button>`).join('')}</div></div>`;ui.selected.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{st.sel.type=b.dataset.type;select(st.sel)});renderIntent();answer();ui.selected.scrollIntoView({behavior:'smooth',block:'start'})}
function renderIntent(){ui.intent.innerHTML=`<h2>Şu anda neye ihtiyacınız var?</h2><div class="chips">${Object.entries(intents).map(([k,v])=>`<button class="pill ${st.intent===k?'active':''}" data-intent="${k}">${v}</button>`).join('')}</div>`;ui.intent.querySelectorAll('[data-intent]').forEach(b=>b.onclick=()=>{st.intent=b.dataset.intent;renderIntent();answer()})}
function lines(){const p=st.sel||{name:'bu ortam',type:'unknown'},n=p.name,t=p.type;let a={bar:[`Merhaba, burayı çok iyi bilmiyorum; burada oturmak için en iyi bölüm neresi sizce?`,`Merhaba, ${n} için tavsiye edeceğiniz içecek veya masa tarafı var mı?`,`Merhaba, ortamı anlamaya çalışıyorum; burada genelde ne tercih ediliyor?`],pub:[`Merhaba, burada oturmak için en iyi köşe neresi sizce?`,`Merhaba, ${n} için ilk kez gelen biri neyi denemeli?`,`Merhaba, burada kalabalık olmadan oturulacak iyi bir taraf var mı?`],cafe:[`Merhaba, burada gerçekten iyi dediğiniz kahve veya tatlı var mı?`,`Merhaba, ${n} için ilk tercih ne olur sizce?`,`Merhaba, kısa bir öneri alabilir miyim; burada ne denemeye değer?`],restaurant:[`Merhaba, menüde kararsız kaldım; burada gerçekten tavsiye edeceğiniz bir şey var mı?`,`Merhaba, ${n} için ilk kez gelen biri neyi kaçırmamalı?`,`Merhaba, burada en güvenli tercih ne olur sizce?`],beauty:[`Merhaba, burayı ilk kez görüyorum; burada hangi hizmet daha çok tavsiye ediliyor?`,`Merhaba, ${n} için kısa bir öneri alabilir miyim; randevu almadan önce neye dikkat edeyim?`,`Merhaba, burada ilk kez işlem yaptıracak biri ne sormalı sizce?`],shop:[`Merhaba, aradığımı hızlı bulmak için hangi tarafa bakmalıyım?`,`Merhaba, ${n} içinde kısa alışveriş için nereden başlamak mantıklı?`,`Merhaba, burada en pratik bölüm neresi?`],beach:[`Merhaba, bu plajda oturmak için en iyi taraf neresi?`,`Merhaba, burada kısa süre kalacak biri hangi noktayı kaçırmamalı?`,`Merhaba, daha sakin oturulacak iyi bir taraf var mı?`],unknown:[`Merhaba, burayı çok iyi bilmiyorum; burada gerçekten tavsiye edeceğiniz bir şey var mı?`,`Merhaba, kısa bir şey sorabilir miyim; burada yeni gelen biri neyi bilmeli?`,`Merhaba, ${n} hakkında hızlı bir öneri alabilir miyim?`]}[t]||[`Merhaba, burayı çok iyi bilmiyorum; burada gerçekten tavsiye edeceğiniz bir şey var mı?`,`Merhaba, ${n} için ilk kez gelen biri nereden başlamalı?`,`Merhaba, kısa bir öneri alabilir miyim; burada neye dikkat edeyim?`];if(st.intent==='silence')a=[`Bu arada, ${n} için sizce en iyi şey ne?`,`Sessiz kalmışken sorayım: burada kaçırılmayacak bir şey var mı?`,`Konu dağılmadan sorayım; burayı tavsiye eder misiniz?`];if(st.intent==='end')a=[`Öneriniz için teşekkür ederim; rahatsız etmeyeyim, iyi vakitler.`,`Çok teşekkürler, yeterince fikir verdi. Size iyi vakitler.`,`Sağ olun, kısa tuttum. Keyfinizi bölmeyeyim.`];return a}
function answer(mode){if(!st.sel)return;let a=lines();if(mode==='next')st.idx=(st.idx+1)%a.length;else st.idx=0;let line=a[st.idx];if(mode==='short')line=line.replace('Merhaba, ','').replace('burayı çok iyi bilmiyorum; ','');if(mode==='warm')line=line.replace('Merhaba,','Merhaba, rahatsız etmiyorsam');if(mode==='direct')line=line.replace('Merhaba, ','').replace('kısa bir şey sorabilir miyim; ','');ui.answer.innerHTML=`<h2>Şimdi söyle</h2><div class="say">“${esc(line)}”</div><div class="why"><b>Neden:</b> Mekân türüne veya seçilen duruma bağlı, düşük baskılı ve cevaplaması kolay bir başlangıç.</div><div class="actions"><button data-mode="short">Daha kısa</button><button data-mode="warm">Daha sıcak</button><button data-mode="direct">Daha doğrudan</button><button data-mode="next">Başka öneri</button></div>`;ui.answer.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>answer(b.dataset.mode))}
ui.q.oninput=()=>{clearTimeout(st.timer);const v=ui.q.value.trim();if(!v){ui.results.innerHTML='';status('Hazır. En az 3 harf yazın veya konumunuzu kullanın.');return}st.timer=setTimeout(()=>search(v),420)};ui.clear.onclick=()=>{ui.q.value='';ui.results.innerHTML='';status('Hazır. En az 3 harf yazın veya konumunuzu kullanın.');ui.q.focus()};ui.loc.onclick=useLoc;ui.voice.onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast('Bu tarayıcıda sesli giriş desteklenmiyor.');return}const r=new SR();r.lang='tr-TR';r.onresult=e=>{ui.q.value=e.results[0][0].transcript;search(ui.q.value)};r.start()};ui.startTab.onclick=()=>document.getElementById('start').scrollIntoView({behavior:'smooth'});ui.rescueTab.onclick=()=>{if(!st.sel){st.sel={name:'bu ortam',address:'Hızlı kurtarma',source:'Kullanıcı girişi',type:'unknown'};ui.intent.classList.remove('hidden');ui.answer.classList.remove('hidden')}st.intent='silence';renderIntent();answer();ui.intent.scrollIntoView({behavior:'smooth'})};ui.privacyTab.onclick=()=>{ui.privacy.classList.toggle('hidden');ui.privacy.scrollIntoView({behavior:'smooth'})};window.addEventListener('online',()=>ui.net.textContent='Çevrimiçi');window.addEventListener('offline',()=>ui.net.textContent='Çevrimdışı');if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js?v=1.4.0').catch(()=>{});
})();