(()=>{'use strict';
const $=id=>document.getElementById(id);const ui={q:$('q'),clear:$('clear'),results:$('results'),status:$('status'),selected:$('selected'),intent:$('intent'),answer:$('answer'),privacy:$('privacy'),loc:$('loc'),voice:$('voice'),net:$('net'),startTab:$('startTab'),rescueTab:$('rescueTab'),privacyTab:$('privacyTab'),toast:$('toast')};
const st={loc:null,sel:null,intent:'approach',timer:0,idx:0,mark:0};
const labels={cafe:'Kafe',restaurant:'Restoran',bar:'Bar',pub:'Pub',fast_food:'Hızlı yemek',food_court:'Yemek alanı',nightclub:'Gece mekânı',beach:'Plaj',park:'Park / açık alan',hotel:'Otel',mall:'AVM / mağaza',shop:'Mağaza',museum:'Müze',attraction:'Turistik yer',transport:'Ulaşım / bekleme alanı',city:'Şehir / bölge',unknown:'Tür bilinmiyor'};
const typeKeys=['cafe','restaurant','bar','pub','beach','park','mall','shop','transport'];const social=new Set(['cafe','restaurant','bar','pub','fast_food','food_court','nightclub','beach','park','hotel','mall','shop','museum','attraction','transport','city']);const intents={approach:'Birine yaklaş',silence:'Sessizlik oldu',group:'Gruba katıl',question:'Bana soru sordu',end:'Kibarca bitir'};
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/\p{Diacritic}/gu,'').replace(/[^a-z0-9]+/g,' ').trim()}
function setStatus(s,k=''){ui.status.textContent=s;ui.status.className='status '+k}
function toast(s){ui.toast.textContent=s;ui.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>ui.toast.classList.remove('show'),2500)}
function req(url,ms=14000){return new Promise((resolve,reject)=>{const c=new AbortController(),t=setTimeout(()=>{c.abort();reject(Error('timeout'))},ms);fetch(url,{signal:c.signal,headers:{accept:'application/json'}}).then(r=>{clearTimeout(t);if(!r.ok)throw Error('http');return r.json()}).then(resolve).catch(e=>{clearTimeout(t);reject(e)})})}
function dist(a,b,c,d){const R=6371,rad=x=>x*Math.PI/180,dl=rad(d-b),dp=rad(c-a),x=Math.sin(dp/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(dl/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function tag(o,k){return (o.tags&&o.tags[k])||(o.extratags&&o.extratags[k])||''}
function nameOf(o){const t=o.tags||o.extratags||{};return t['name:tr']||t['name:en']||t.brand||t.name||o.name||(o.display_name||'').split(',')[0]||'Sonuç'}
function addressOf(o){const t=o.tags||{},a=o.address||{};const parts=[t['addr:street']||a.road||a.pedestrian||a.neighbourhood||a.suburb||a.quarter,t['addr:city']||a.city||a.town||a.village||a.state,t['addr:country']||a.country].filter(Boolean);return parts.length?parts.join(', '):(o.display_name||'').split(',').slice(1,4).join(', ')||'Yakındaki açık veri kaydı'}
function classify(o){const t=o.tags||o.extratags||{},cls=(o.class||'').toLowerCase(),typ=(o.type||'').toLowerCase(),nm=norm(nameOf(o));const vals=[t.amenity,t.shop,t.tourism,t.leisure,t.natural,t.railway,t.public_transport,t.place,typ,cls].filter(Boolean).map(x=>String(x).toLowerCase());
if(vals.includes('bar')||/\bbar\b/.test(nm))return'bar';if(vals.includes('pub'))return'pub';if(vals.includes('cafe')||/\bcafe|coffee|kahve\b/.test(nm))return'cafe';if(vals.includes('restaurant')||/restaurant|restoran|grill|kitchen|diner|steak|pizza|burger|sushi|bistro|trattoria/.test(nm))return'restaurant';if(vals.includes('food_court'))return'food_court';if(vals.includes('fast_food'))return'fast_food';if(vals.includes('nightclub'))return'nightclub';if(vals.includes('beach')||/beach|plaj/.test(nm))return'beach';if(vals.includes('park')||vals.includes('garden'))return'park';if(vals.includes('hotel')||vals.includes('resort')||vals.includes('guest_house'))return'hotel';if(vals.some(v=>['mall','shopping_centre','department_store'].includes(v)))return'mall';if(vals.some(v=>['convenience','supermarket','bakery','books','clothes','shop'].includes(v))||/eleven|7 eleven|7-eleven|store|market|shop/.test(nm))return'shop';if(vals.includes('museum'))return'museum';if(vals.includes('attraction')||vals.includes('viewpoint'))return'attraction';if(vals.some(v=>['station','bus_station','ferry_terminal','airport','platform','tram_stop'].includes(v)))return'transport';if(vals.some(v=>['city','town','village','suburb','neighbourhood'].includes(v)))return'city';return'unknown'}
function place(o,source){const lat=+(o.lat||(o.center&&o.center.lat)),lon=+(o.lon||(o.center&&o.center.lon));const p={id:source+':' +(o.osm_type||o.type||'')+':' +(o.osm_id||o.id||nameOf(o)+lat+lon),name:nameOf(o),address:addressOf(o),lat,lon,source,type:classify(o),raw:o};p.distance=st.loc&&lat&&lon?dist(st.loc.lat,st.loc.lon,lat,lon):null;return p}
function unique(arr){const m=new Map();for(const p of arr){if(!p.lat||!p.lon||!p.name)continue;const key=norm(p.name)+'|'+Math.round(p.lat*1000)+'|'+Math.round(p.lon*1000);if(!m.has(key)||score(p)>score(m.get(key)))m.set(key,p)}return [...m.values()]}
function score(p){let s=0;if(p.distance!=null)s+=Math.max(0,500-p.distance*20);if(p.source.startsWith('Yakın'))s+=150;if(p.type!=='unknown')s+=100;if(['restaurant','cafe','bar','pub','shop','beach','park'].includes(p.type))s+=40;return s}
function order(arr,q){const nq=norm(q);return arr.sort((a,b)=>{const ax=norm(a.name)===nq?1:0,bx=norm(b.name)===nq?1:0;if(ax!==bx)return bx-ax;if(st.loc&&a.distance!=null&&b.distance!=null)return a.distance-b.distance;return score(b)-score(a)})}
function show(list,msg){ui.results.innerHTML='';if(!list.length){setStatus(msg||'Uygun açık veri sonucu bulunamadı. Mekân adıyla birlikte semt/şehir yazın.','warn');return}setStatus(msg||`${list.length} sonuç bulundu. Doğru mekânı seçin.`,'good');list.forEach(p=>{const d=p.distance!=null?` • ${p.distance<1?Math.round(p.distance*1000)+' m':p.distance.toFixed(1)+' km'}`:'';const b=document.createElement('button');b.className='result';b.innerHTML=`<strong>${esc(p.name)}</strong><small>${esc(p.address)}${d}</small><span class="tag ${p.type==='unknown'?'warn':'good'}">${esc(labels[p.type]||labels.unknown)} · ${esc(p.source)}</span>`;b.onclick=()=>select(p);ui.results.appendChild(b)})}
function socialOnly(arr,allowUnknown=false){const known=arr.filter(p=>social.has(p.type)&&p.type!=='unknown');if(known.length)return known;return allowUnknown?arr.filter(p=>p.type!=='unknown').concat(arr.filter(p=>p.type==='unknown').slice(0,3)):[]}
function re(s){return norm(s).replace(/ /g,'.*').replace(/[^a-z0-9.*-]/g,'')}
function bbox(r){return [st.loc.lon-r,st.loc.lat+r,st.loc.lon+r,st.loc.lat-r].join(',')}
async function nominatimLocal(q){if(!st.loc)return[];const url=`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=30&addressdetails=1&extratags=1&dedupe=1&accept-language=tr,en&viewbox=${bbox(.35)}&bounded=1&q=${encodeURIComponent(q)}`;return (await req(url,12000)).map(x=>place(x,'OpenStreetMap'))}
async function nominatimGlobal(q){const url=`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=20&addressdetails=1&extratags=1&dedupe=1&accept-language=tr,en&q=${encodeURIComponent(q)}`;return (await req(url,12000)).map(x=>place(x,'OpenStreetMap'))}
async function overpassNamed(q,radius=30000){if(!st.loc)return[];const data=`[out:json][timeout:14];(nwr(around:${radius},${st.loc.lat},${st.loc.lon})["name"~"${re(q)}",i]["amenity"];nwr(around:${radius},${st.loc.lat},${st.loc.lon})["name"~"${re(q)}",i]["shop"];nwr(around:${radius},${st.loc.lat},${st.loc.lon})["name"~"${re(q)}",i]["tourism"];nwr(around:${radius},${st.loc.lat},${st.loc.lon})["name"~"${re(q)}",i]["leisure"];nwr(around:${radius},${st.loc.lat},${st.loc.lon})["name"~"${re(q)}",i]["natural"="beach"];);out center tags 50;`;const j=await req('https://overpass-api.de/api/interpreter?data='+encodeURIComponent(data),15000);return (j.elements||[]).map(e=>place({id:e.id,type:e.type,lat:e.lat,lon:e.lon,center:e.center,tags:e.tags||{}},'Yakın açık veri'))}
async function overpassNearby(radius){const data=`[out:json][timeout:14];(nwr(around:${radius},${st.loc.lat},${st.loc.lon})["name"]["amenity"~"^(cafe|restaurant|bar|pub|fast_food|food_court|nightclub|marketplace|cinema|theatre|ferry_terminal|bus_station)$"];nwr(around:${radius},${st.loc.lat},${st.loc.lon})["name"]["shop"~"^(mall|convenience|supermarket|department_store|bakery|books|clothes)$"];nwr(around:${radius},${st.loc.lat},${st.loc.lon})["name"]["tourism"~"^(attraction|museum|hotel|viewpoint)$"];nwr(around:${radius},${st.loc.lat},${st.loc.lon})["name"]["leisure"~"^(park|garden)$"];nwr(around:${radius},${st.loc.lat},${st.loc.lon})["name"]["natural"="beach"];);out center tags 60;`;const j=await req('https://overpass-api.de/api/interpreter?data='+encodeURIComponent(data),15000);return (j.elements||[]).map(e=>place({id:e.id,type:e.type,lat:e.lat,lon:e.lon,center:e.center,tags:e.tags||{}},'Yakın açık veri'))}
async function search(q){q=q.trim();if(q.length<2){ui.results.innerHTML='';setStatus('Birkaç harf daha yazın veya konumunuzu kullanın.');return}const mark=++st.mark;setStatus(st.loc?'Yakın açık veri aranıyor…':'Açık veri aranıyor…');try{let arr=[];if(st.loc){const res=(await Promise.allSettled([overpassNamed(q,30000),nominatimLocal(q)])).flatMap(x=>x.status==='fulfilled'?x.value:[]);arr=order(unique(res).filter(p=>p.distance==null||p.distance<=80),q);arr=socialOnly(arr,true).slice(0,10);if(mark!==st.mark)return;if(arr.length)show(arr,`${arr.length} yakın sonuç bulundu. Doğru mekânı seçin.`);else show([],`Konumunuza yakın “${q}” sonucu bulunamadı. Mekân adını şehir/semt ile yazın veya yakındaki listeden seçim yapın.`);return}
arr=order(unique(await nominatimGlobal(q)),q).slice(0,10);if(mark!==st.mark)return;show(arr,`${arr.length} açık veri sonucu bulundu. Doğru mekânı seçin.`)}catch(e){if(mark!==st.mark)return;show([], 'Açık veri araması şu anda yanıt vermedi. Konumu kullanın veya şehir ekleyerek tekrar deneyin.')}}
async function nearby(){if(!st.loc)return;setStatus('Yakındaki sosyal mekânlar aranıyor…');for(const r of [1000,2500,6000,12000]){try{let arr=order(unique(await overpassNearby(r)),'').filter(p=>p.distance<=r/1000);arr=socialOnly(arr,false).slice(0,12);if(arr.length){show(arr,`${arr.length} yakın sosyal mekân bulundu. Doğru olanı seçin.`);return}}catch(e){}}
show([], 'Konum alındı, fakat yakın sosyal mekân listesi alınamadı. Mekân adını yazın; bu konum içinde arayacağım.')}
function useLocation(){ui.loc.disabled=true;setStatus('Konum izni bekleniyor…');navigator.geolocation.getCurrentPosition(pos=>{st.loc={lat:pos.coords.latitude,lon:pos.coords.longitude};ui.loc.disabled=false;setStatus('Konum alındı. Yakındaki sosyal mekânlar aranıyor…','good');nearby();if(ui.q.value.trim().length>1)search(ui.q.value)},()=>{ui.loc.disabled=false;setStatus('Konum alınamadı. Android/Chrome konum iznini kontrol edin veya mekân adı + şehir yazın.','bad')},{enableHighAccuracy:true,timeout:12000,maximumAge:120000})}
function select(p){st.sel=p;st.idx=0;ui.selected.classList.remove('hidden');ui.intent.classList.remove('hidden');ui.answer.classList.remove('hidden');const trust=p.source.startsWith('Yakın')&&p.type!=='unknown'?'Yüksek':(p.type==='unknown'?'Orta':'Yüksek');ui.selected.innerHTML=`<div class="selected"><div class="venue-title"><div><h2>${esc(p.name)}</h2><p>${esc(p.address)}</p></div><span class="badge ${trust==='Orta'?'medium':''}">Güven: ${trust}</span></div><div class="meta"><div>Tür <b>${esc(labels[p.type]||labels.unknown)}</b></div><div>Kaynak <b>Açık veri</b></div>${p.distance!=null?`<div>Mesafe <b>${p.distance<1?Math.round(p.distance*1000)+' m':p.distance.toFixed(1)+' km'}</b></div>`:''}</div>${p.type==='unknown'?'<p>Tür net değilse tek dokunuşla düzeltin:</p>':''}<div class="chips">${typeKeys.map(t=>`<button class="pill ${p.type===t?'active':''}" data-type="${t}">${labels[t]}</button>`).join('')}</div></div>`;ui.selected.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{st.sel.type=b.dataset.type;select(st.sel)});renderIntent();answer();ui.selected.scrollIntoView({behavior:'smooth',block:'start'})}
function renderIntent(){ui.intent.innerHTML=`<h2>Şu anda neye ihtiyacınız var?</h2><div class="chips">${Object.entries(intents).map(([k,v])=>`<button class="pill ${st.intent===k?'active':''}" data-intent="${k}">${v}</button>`).join('')}</div>`;ui.intent.querySelectorAll('[data-intent]').forEach(b=>b.onclick=()=>{st.intent=b.dataset.intent;renderIntent();answer()})}
function lines(){const p=st.sel||{name:'bu yer',type:'unknown'},n=p.name,t=p.type;const base={restaurant:[`Merhaba, burayı çok iyi bilmiyorum; burada gerçekten tavsiye edeceğiniz bir şey var mı?`,`Merhaba, menüde hızlıca doğru seçimi yapmak istiyorum. Burada en çok ne önerirsiniz?`,`Merhaba, ${n} için ilk kez karar verecek biri neyi kaçırmamalı sizce?`],bar:[`Merhaba, ortamı çok iyi bilmiyorum; burada oturmak için en iyi bölüm neresi sizce?`,`Merhaba, burada içecek ya da atmosfer olarak gerçekten tavsiye edeceğiniz bir şey var mı?`,`Merhaba, ${n} için kısa bir öneri alabilir miyim; burada en mantıklı tercih ne olur?`],pub:[`Merhaba, burada oturmak için en iyi köşe neresi sizce?`,`Merhaba, ${n} için tavsiye edeceğiniz içecek veya masa tarafı var mı?`,`Merhaba, ortamı çok iyi bilmiyorum; burada genelde ne tercih ediliyor?`],cafe:[`Merhaba, burada kahve için gerçekten iyi dediğiniz bir seçenek var mı?`,`Merhaba, ${n} için ilk tercih ne olur sizce; kahve mi tatlı mı?`,`Merhaba, kısa bir öneri alabilir miyim; burada ne denemeye değer?`],beach:[`Merhaba, burayı çok iyi bilmiyorum; burada deniz/gün batımı için en iyi taraf neresi?`,`Merhaba, bu plajda kısa süre kalacak biri hangi noktayı kaçırmamalı?`,`Merhaba, burada daha sakin oturulacak iyi bir taraf var mı?`],shop:[`Merhaba, burada aradığımı hızlı bulmak için hangi tarafa bakmalıyım?`,`Merhaba, kısa bir şey sorabilir miyim; burada en pratik bölüm neresi?`,`Merhaba, ${n} içinde hızlı alışveriş için nereden başlamak mantıklı?`],mall:[`Merhaba, burada hızlıca iyi bir yer bulmak istiyorum; hangi taraf daha mantıklı?`,`Merhaba, bu AVM’de kısa zaman için en iyi seçenek neresi?`,`Merhaba, burada yemek/kahve için gerçekten tavsiye edeceğiniz bir yer var mı?`],unknown:[`Merhaba, burayı çok iyi bilmiyorum; burada gerçekten tavsiye edeceğiniz bir şey var mı?`,`Merhaba, kısa bir şey sorabilir miyim; burada yeni gelen biri neyi bilmeli?`,`Merhaba, ${n} hakkında hızlı bir öneri alabilir miyim?`]};let a=base[t]||base.unknown;if(st.intent==='silence')a=[`Bu arada, ${n} için sizce en iyi şey ne?`,`Sessiz kalmışken sorayım: burada kaçırılmayacak bir şey var mı?`,`Konu dağılmadan sorayım; burayı tavsiye eder misiniz?`];if(st.intent==='group')a=[`Merhaba, rahatsız etmiyorsam kısa bir öneri alayım: burada en mantıklı tercih ne?`,`Selam, gruba dahil olmadan sadece bir şey sorayım; burada neyi tavsiye edersiniz?`,`Merhaba, burayı çok iyi bilmiyorum; sizce nereden başlamak lazım?`];if(st.intent==='question')a=[`Güzel soru; ben de burayı anlamaya çalışıyorum. Siz ne önerirsiniz?`,`Ben de emin değilim; birlikte en mantıklı seçeneği bulalım mı?`,`Aslında tam onu merak ediyordum; sizin ilk izleniminiz ne?`];if(st.intent==='end')a=[`Öneriniz için teşekkür ederim; rahatsız etmeyeyim, iyi vakitler.`,`Çok teşekkürler, yeterince fikir verdi. Size iyi akşamlar.`,`Sağ olun, kısa tuttum. Keyfinizi bölmeyeyim.`];return a}
function answer(mode){if(!st.sel)return;let a=lines();if(mode==='short')a=a.map(x=>x.replace('Merhaba, ','').replace('kısa bir şey sorabilir miyim; ','').replace('burayı çok iyi bilmiyorum; ',''));if(mode==='warm')a=a.map(x=>x.replace('Merhaba,','Merhaba, rahatsız etmiyorsam').replace('Selam,','Selam, rahatsız etmiyorsam'));if(mode==='direct')a=a.map(x=>x.replace('Merhaba, ','').replace('rahatsız etmiyorsam ','').replace('kısa bir şey sorabilir miyim; ',''));if(mode==='next')st.idx=(st.idx+1)%a.length;else st.idx=0;const line=a[st.idx%a.length];ui.answer.innerHTML=`<h2>Şimdi söyle</h2><div class="say">“${esc(line)}”</div><div class="why"><b>Neden:</b> Mekâna veya seçilen duruma bağlı, düşük baskılı ve cevaplaması kolay bir başlangıç. Bilmediği şeyi biliyormuş gibi iddia etmez.</div><div class="actions"><button data-mode="short">Daha kısa</button><button data-mode="warm">Daha sıcak</button><button data-mode="direct">Daha doğrudan</button><button data-mode="next">Başka öneri</button></div>`;ui.answer.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>answer(b.dataset.mode))}
ui.q.oninput=()=>{clearTimeout(st.timer);const v=ui.q.value.trim();if(!v){ui.results.innerHTML='';setStatus('Hazır. Birkaç harf yazın veya konumunuzu kullanın.');return}st.timer=setTimeout(()=>search(v),430)};ui.clear.onclick=()=>{ui.q.value='';ui.results.innerHTML='';setStatus('Hazır. Birkaç harf yazın veya konumunuzu kullanın.');ui.q.focus()};ui.loc.onclick=useLocation;ui.voice.onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast('Bu tarayıcıda sesli giriş desteklenmiyor.');return}const r=new SR();r.lang='tr-TR';r.onresult=e=>{ui.q.value=e.results[0][0].transcript;search(ui.q.value)};r.onerror=()=>toast('Ses alınamadı.');r.start()};ui.startTab.onclick=()=>document.getElementById('start').scrollIntoView({behavior:'smooth'});ui.rescueTab.onclick=()=>{if(!st.sel){st.sel={name:'bu ortam',address:'Hızlı kurtarma',source:'Açık veri',type:'unknown'};ui.intent.classList.remove('hidden');ui.answer.classList.remove('hidden')}st.intent='silence';renderIntent();answer();ui.intent.scrollIntoView({behavior:'smooth'})};ui.privacyTab.onclick=()=>{ui.privacy.classList.toggle('hidden');ui.privacy.scrollIntoView({behavior:'smooth'})};window.addEventListener('online',()=>ui.net.textContent='Çevrimiçi');window.addEventListener('offline',()=>ui.net.textContent='Çevrimdışı');if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js?v=1.3.0').catch(()=>{});
})();