(()=>{'use strict';
const $=id=>document.getElementById(id);
const ui={q:$('q'),clear:$('clear'),results:$('results'),status:$('status'),selected:$('selected'),intent:$('intent'),answer:$('answer'),privacy:$('privacy'),loc:$('loc'),voice:$('voice'),net:$('net'),startTab:$('startTab'),rescueTab:$('rescueTab'),privacyTab:$('privacyTab'),toast:$('toast')};
const NEAR=[100,200,500],MAX_LOCAL=.5,MAX_EXPAND=3;
const st={loc:null,locTried:false,cache:null,cacheR:0,sel:null,intent:'approach',timer:0,mark:0,idx:0,expanded:false};
const labels={cafe:'Kafe',restaurant:'Restoran',bar:'Bar',pub:'Pub',fast_food:'Hızlı yemek',food_court:'Yemek alanı',nightclub:'Gece mekânı',beach:'Plaj',park:'Park / açık alan',hotel:'Otel',mall:'AVM / mağaza',shop:'Mağaza',salon:'Kuaför / bakım',museum:'Müze',attraction:'Turistik yer',transport:'Ulaşım / bekleme alanı',city:'Şehir / bölge',unknown:'Tür bilinmiyor'};
const typeKeys=['cafe','restaurant','bar','pub','shop','salon','beach','park','mall','transport'];
const intents={approach:'Birine yaklaş',silence:'Sessizlik oldu',group:'Gruba katıl',question:'Bana soru sordu',end:'Kibarca bitir'};
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/\p{Diacritic}/gu,'').replace(/[^a-z0-9]+/g,' ').trim()}
function toks(s){return norm(s).split(' ').filter(x=>x.length>1&&!['the','and','hotel','cafe','restaurant','restoran','bar','shop','store','muscat','oman','umman','seeb'].includes(x))}
function status(s,k=''){ui.status.textContent=s;ui.status.className='status '+k}
function toast(s){ui.toast.textContent=s;ui.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>ui.toast.classList.remove('show'),2500)}
function km(a,b,c,d){const R=6371,rad=x=>x*Math.PI/180,dl=rad(d-b),dp=rad(c-a),z=Math.sin(dp/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(dl/2)**2;return R*2*Math.atan2(Math.sqrt(z),Math.sqrt(1-z))}
function json(url,ms=12000){return new Promise((res,rej)=>{const c=new AbortController(),t=setTimeout(()=>{c.abort();rej(Error('timeout'))},ms);fetch(url,{signal:c.signal,headers:{accept:'application/json'}}).then(r=>{clearTimeout(t);if(!r.ok)throw Error('http');return r.json()}).then(res).catch(e=>{clearTimeout(t);rej(e)})})}
function lev(a,b){a=norm(a);b=norm(b);let m=a.length,n=b.length,dp=Array(n+1).fill(0).map((_,i)=>i);for(let i=1;i<=m;i++){let p=dp[0];dp[0]=i;for(let j=1;j<=n;j++){let tmp=dp[j];dp[j]=Math.min(dp[j]+1,dp[j-1]+1,p+(a[i-1]===b[j-1]?0:1));p=tmp}}return dp[n]}
function fuzzy(q,name){const qv=toks(q),nv=toks(name);if(!qv.length||!nv.length)return 0;let total=0;for(const a of qv){let best=0;for(const b of nv){if(b.startsWith(a)||a.startsWith(b))best=Math.max(best,.96);else{const d=lev(a,b),r=1-d/Math.max(a.length,b.length);if(d<=1&&a.length>=4)best=Math.max(best,.9);else if(d<=2&&a.length>=5)best=Math.max(best,.74);else best=Math.max(best,r)}}total+=best}return total/qv.length}
function relevant(p,q){return fuzzy(q,p.name)>=.58||(p.type==='city'&&norm(p.name).includes(norm(q)))}
function classify(o){const t=o.tags||o.extratags||{},cls=(o.class||'').toLowerCase(),typ=(o.type||'').toLowerCase(),name=norm(o.name||o.display_name);const vals=[t.amenity,t.shop,t.tourism,t.leisure,t.natural,t.place,typ,cls].filter(Boolean).map(x=>String(x).toLowerCase());
if(vals.includes('hairdresser')||vals.includes('beauty')||vals.includes('cosmetics')||/coiffure|kuafor|kuaför|salon|barber|hair|beauty/.test(name))return'salon';
if(vals.includes('bar')||/\bbar\b/.test(name))return'bar';if(vals.includes('pub')||vals.includes('biergarten'))return'pub';if(vals.includes('cafe')||/\bcafe|coffee|kahve\b/.test(name))return'cafe';
if(vals.includes('restaurant')||/restaurant|restoran|grill|kitchen|diner|steak|pizza|burger|sushi|trattoria|bistro/.test(name))return'restaurant';if(vals.includes('fast_food')||vals.includes('food_court'))return vals.includes('food_court')?'food_court':'fast_food';if(vals.includes('nightclub'))return'nightclub';if(vals.includes('beach')||vals.includes('beach_resort')||/beach|plaj/.test(name))return'beach';if(vals.includes('park')||vals.includes('garden'))return'park';if(vals.includes('hotel')||vals.includes('guest_house')||vals.includes('resort'))return'hotel';if(vals.includes('mall')||vals.includes('shopping_centre'))return'mall';if(vals.some(v=>['supermarket','convenience','department_store','kiosk'].includes(v))||/7 eleven|7-eleven|eleven|store|market|shop/.test(name))return'shop';if(vals.includes('museum'))return'museum';if(vals.some(v=>['attraction','viewpoint','artwork'].includes(v)))return'attraction';if(vals.some(v=>['station','bus_station','ferry_terminal','airport','platform'].includes(v)))return'transport';if(vals.some(v=>['city','town','village','suburb','neighbourhood'].includes(v)))return'city';return'unknown'}
function addr(o){const a=o.address||{},p=[a.road||a.pedestrian||a.neighbourhood||a.suburb||a.quarter,a.city||a.town||a.village||a.state,a.country].filter(Boolean);return p.length?p.join(', '):(o.display_name||'').split(',').slice(1,4).join(', ')}
function place(o,src){const tags=o.tags||o.extratags||{},lat=+(o.lat||(o.center&&o.center.lat)),lon=+(o.lon||(o.center&&o.center.lon));const name=o.name||tags.name||(o.namedetails&&(o.namedetails.name||o.namedetails['name:en']))||o.display_name?.split(',')[0]||'Sonuç';let p={id:src+':'+(o.osm_type||o.type||'')+':'+(o.osm_id||o.id||name+lat+lon),name,lat,lon,address:addr(o),source:src,type:classify({...o,tags}),raw:o};p.distance=st.loc&&lat&&lon?km(st.loc.lat,st.loc.lon,lat,lon):null;return p}
function photon(f){const p=f.properties||{};return place({id:p.osm_id,lat:f.geometry?.coordinates?.[1],lon:f.geometry?.coordinates?.[0],name:p.name,display_name:[p.name,p.street,p.city,p.state,p.country].filter(Boolean).join(', '),type:p.osm_value,class:p.osm_key,tags:{[p.osm_key]:p.osm_value},address:{road:p.street,city:p.city||p.state,country:p.country}},'Harita verisi')}
function dedupe(arr){const m=new Map();for(const p of arr){if(!p.lat||!p.lon)continue;const k=norm(p.name)+'|'+Math.round(p.lat*10000)+'|'+Math.round(p.lon*10000);const old=m.get(k);if(!old||(p.distance??99)<(old.distance??99))m.set(k,p)}return[...m.values()]}
function rank(a,q){return a.sort((x,y)=>{const dx=x.distance??9999,dy=y.distance??9999;if(Math.abs(dx-dy)>.05)return dx-dy;return fuzzy(q,y.name)-fuzzy(q,x.name)})}
function render(list,msg){ui.results.innerHTML='';if(!list.length){status(msg||'Yakın çevrede uygun sonuç bulunamadı. Mekân adını/şehri netleştirin veya konumu kontrol edin.','warn');return}status(msg||`${list.length} yakın sonuç bulundu. Doğru mekânı seçin.`,'good');for(const p of list){const d=p.distance!=null?` • ${p.distance<1?Math.round(p.distance*1000)+' m':p.distance.toFixed(1)+' km'}`:'';const b=document.createElement('button');b.className='result';b.innerHTML=`<strong>${esc(p.name)}</strong><small>${esc(p.address||'Adres bilgisi yok')}${d}</small><span class='tag ${p.type==='unknown'?'warn':'good'}'>${esc(labels[p.type]||labels.unknown)} · ${esc(p.source)}</span>`;b.onclick=()=>select(p);ui.results.appendChild(b)}}
function expandBtn(q){const b=document.createElement('button');b.className='result';b.style.borderStyle='dashed';b.innerHTML=`<strong>Yakını genişlet</strong><small>500 m içinde sonuç yoksa 3 km’ye kadar arar. Uzak şehir/ülke sonuçları göstermez.</small><span class='tag warn'>Kontrollü genişletme</span>`;b.onclick=()=>{st.expanded=true;search(q,true)};ui.results.appendChild(b)}
async function askLoc(silent=false){if(st.loc)return true;st.locTried=true;try{const pos=await new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(res,rej,{enableHighAccuracy:true,timeout:9000,maximumAge:90000}));st.loc={lat:pos.coords.latitude,lon:pos.coords.longitude,ts:Date.now()};localStorage.setItem('firststepLoc',JSON.stringify(st.loc));return true}catch(e){if(!silent)status('Konum alınamadı. Android/Chrome konum iznini kontrol edin.','bad');return false}}
function loadLoc(){try{const x=JSON.parse(localStorage.getItem('firststepLoc')||'null');if(x&&Date.now()-x.ts<21600000)st.loc=x}catch(e){}}
function overpass(r){const data=`[out:json][timeout:12];(nwr(around:${r},${st.loc.lat},${st.loc.lon})['name']['amenity'];nwr(around:${r},${st.loc.lat},${st.loc.lon})['name']['shop'];nwr(around:${r},${st.loc.lat},${st.loc.lon})['name']['tourism'];nwr(around:${r},${st.loc.lat},${st.loc.lon})['name']['leisure'];nwr(around:${r},${st.loc.lat},${st.loc.lon})['name']['natural'];);out center tags 80;`;return json('https://overpass-api.de/api/interpreter?data='+encodeURIComponent(data),14000).then(j=>(j.elements||[]).map(e=>place({id:e.id,lat:e.lat,lon:e.lon,center:e.center,tags:e.tags||{},name:e.tags&&e.tags.name,type:e.type},'Yakın harita verisi'))).catch(()=>[])}
async function localPool(maxR=500){if(!st.loc)return[];if(st.cache&&st.cacheR>=maxR)return st.cache;let arr=[];for(const r of NEAR){arr=await overpass(r);if(arr.length||r>=maxR){st.cache=arr;st.cacheR=r;return arr}}return arr}
async function search(q,expanded=false){q=q.trim();if(q.length<3){ui.results.innerHTML='';status('En az 3 harf yazın.');return}const mark=++st.mark;status(st.loc?'Yakındaki eşleşmeler aranıyor…':'Konum hazırlanıyor…');if(!st.loc&&!st.locTried)await askLoc(true);let out=[];
if(st.loc){let pool=await localPool(500);if(mark!==st.mark)return;out=rank(dedupe(pool.filter(p=>p.distance!=null&&p.distance<=MAX_LOCAL&&relevant(p,q))),q);if(!out.length){const box=`${st.loc.lon-.02},${st.loc.lat+.02},${st.loc.lon+.02},${st.loc.lat-.02}`;const [ph,nom]=await Promise.all([json(`https://photon.komoot.io/api/?q=${encodeURIComponent(q)}&limit=20&lat=${st.loc.lat}&lon=${st.loc.lon}`,10000).then(j=>(j.features||[]).map(photon)).catch(()=>[]),json(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=20&addressdetails=1&extratags=1&namedetails=1&dedupe=1&accept-language=tr,en&viewbox=${box}&bounded=0&q=${encodeURIComponent(q)}`,10000).then(a=>a.map(x=>place(x,'Harita verisi'))).catch(()=>[])]);out=rank(dedupe([...ph,...nom].filter(p=>p.distance!=null&&p.distance<=MAX_LOCAL&&relevant(p,q))),q)}if(out.length){render(out.slice(0,8),`${out.length} yakın sonuç bulundu. Doğru mekânı seçin.`);return}if(expanded||st.expanded){let big=await overpass(3000);if(mark!==st.mark)return;out=rank(dedupe(big.filter(p=>p.distance!=null&&p.distance<=MAX_EXPAND&&relevant(p,q))),q);render(out.slice(0,10),out.length?`${out.length} genişletilmiş yakın sonuç bulundu. Doğru mekânı seçin.`:'3 km içinde eşleşme yok. Mekân adını veya bölgeyi düzeltin.');return}ui.results.innerHTML='';status('500 m içinde eşleşen mekân bulunamadı.','warn');expandBtn(q);return}
const [ph,nom]=await Promise.all([json(`https://photon.komoot.io/api/?q=${encodeURIComponent(q)}&limit=12`,10000).then(j=>(j.features||[]).map(photon)).catch(()=>[]),json(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=12&addressdetails=1&extratags=1&namedetails=1&dedupe=1&accept-language=tr,en&q=${encodeURIComponent(q)}`,10000).then(a=>a.map(x=>place(x,'Harita verisi'))).catch(()=>[])]);if(mark!==st.mark)return;out=rank(dedupe([...ph,...nom].filter(p=>relevant(p,q))),q);render(out.slice(0,10),out.length?`${out.length} açık veri sonucu bulundu. Doğru mekânı seçin.`:'Açık veride eşleşme yok. Yazımı veya şehir bilgisini düzeltin.')}
async function nearby(){status('Yakındaki mekânlar aranıyor…');let arr=[];for(const r of NEAR){arr=rank(dedupe((await overpass(r)).filter(p=>p.distance!=null&&p.distance<=r/1000)),'');if(arr.length){render(arr.slice(0,12),`${r} m içinde ${arr.length} mekân bulundu. Doğru olanı seçin.`);return}}status('500 m içinde açık harita mekânı bulunamadı. Mekân adını yazın; yakın çevrede eşleşme arayacağım.','warn')}
async function useLocation(){ui.loc.disabled=true;status('Konum izni bekleniyor…');const ok=await askLoc(false);ui.loc.disabled=false;if(ok){status('Konum alındı. Yakındaki mekânlar aranıyor…','good');nearby();if(ui.q.value.trim().length>=3)search(ui.q.value.trim())}}
function select(p){st.sel=p;st.idx=0;ui.selected.classList.remove('hidden');ui.intent.classList.remove('hidden');ui.answer.classList.remove('hidden');const trust=p.source.includes('Kullanıcı')?'Düşük':(p.type==='unknown'?'Orta':'Yüksek'),badge=trust==='Yüksek'?'badge':'badge medium';ui.selected.innerHTML=`<div class='selected'><div class='venue-title'><div><h2>${esc(p.name)}</h2><p>${esc(p.address||'Adres bilgisi yok')}</p></div><span class='${badge}'>Güven: ${trust}</span></div><div class='meta'><div>Tür <b>${esc(labels[p.type]||labels.unknown)}</b></div><div>Kaynak <b>${esc(p.source.includes('Kullanıcı')?'Kullanıcı girişi':'Açık harita verisi')}</b></div>${p.distance!=null?`<div>Mesafe <b>${p.distance<1?Math.round(p.distance*1000)+' m':p.distance.toFixed(1)+' km'}</b></div>`:''}</div>${p.type==='unknown'?'<p>Tür net değilse tek dokunuşla düzeltin:</p>':''}<div class='chips'>${typeKeys.map(t=>`<button class='pill ${p.type===t?'active':''}' data-type='${t}'>${labels[t]}</button>`).join('')}</div></div>`;ui.selected.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{st.sel.type=b.dataset.type;select(st.sel)});renderIntent();answer();ui.selected.scrollIntoView({behavior:'smooth',block:'start'})}
function renderIntent(){ui.intent.innerHTML=`<h2>Şu anda neye ihtiyacınız var?</h2><div class='chips'>${Object.entries(intents).map(([k,v])=>`<button class='pill ${st.intent===k?'active':''}' data-intent='${k}'>${v}</button>`).join('')}</div>`;ui.intent.querySelectorAll('[data-intent]').forEach(b=>b.onclick=()=>{st.intent=b.dataset.intent;renderIntent();answer()})}
function lines(){const p=st.sel||{name:'bu yer',type:'unknown'},n=p.name,t=p.type;let m={restaurant:[`Merhaba, burayı çok iyi bilmiyorum; burada gerçekten tavsiye edeceğiniz bir şey var mı?`,`Merhaba, menüde hızlıca doğru seçimi yapmak istiyorum. Burada en çok ne önerirsiniz?`,`Merhaba, ${n} için ilk kez karar verecek biri neyi kaçırmamalı sizce?`],bar:[`Merhaba, ortamı çok iyi bilmiyorum; burada oturmak için en iyi bölüm neresi sizce?`,`Merhaba, burada içecek ya da atmosfer olarak gerçekten tavsiye edeceğiniz bir şey var mı?`,`Merhaba, ${n} için kısa bir öneri alabilir miyim; burada en mantıklı tercih ne olur?`],pub:[`Merhaba, burada oturmak için en iyi köşe neresi sizce?`,`Merhaba, ${n} için tavsiye edeceğiniz içecek veya masa tarafı var mı?`,`Merhaba, ortamı çok iyi bilmiyorum; burada genelde ne tercih ediliyor?`],cafe:[`Merhaba, burada kahve için gerçekten iyi dediğiniz bir seçenek var mı?`,`Merhaba, ${n} için ilk tercih ne olur sizce; kahve mi tatlı mı?`,`Merhaba, kısa bir öneri alabilir miyim; burada ne denemeye değer?`],salon:[`Merhaba, burayı ilk kez deneyeceğim; burada özellikle kimi ya da hangi işlemi tavsiye edersiniz?`,`Merhaba, kısa bir şey sorabilir miyim; burada randevu/işlem için en doğru başlangıç ne olur?`,`Merhaba, ${n} için ilk kez gelen biri neyi bilirse iyi olur?`],shop:[`Merhaba, burada aradığımı hızlı bulmak için hangi tarafa bakmalıyım?`,`Merhaba, kısa bir şey sorabilir miyim; burada en pratik bölüm neresi?`,`Merhaba, ${n} içinde hızlı alışveriş için nereden başlamak mantıklı?`],unknown:[`Merhaba, burayı çok iyi bilmiyorum; burada gerçekten tavsiye edeceğiniz bir şey var mı?`,`Merhaba, kısa bir şey sorabilir miyim; burada yeni gelen biri neyi bilmeli?`,`Merhaba, ${n} hakkında hızlı bir öneri alabilir miyim?`]};let a=m[t]||m.unknown;if(st.intent==='silence')a=[`Bu arada, ${n} için sizce en iyi şey ne?`,`Sessiz kalmışken sorayım: burada kaçırılmayacak bir şey var mı?`,`Konu dağılmadan sorayım; burayı tavsiye eder misiniz?`];if(st.intent==='group')a=[`Merhaba, rahatsız etmiyorsam kısa bir öneri alabilir miyim: burada en mantıklı tercih ne?`,`Selam, gruba dahil olmadan sadece bir öneri alayım: burada neyi kaçırmamak lazım?`,`Merhaba, burayı çok iyi bilmiyorum; sizce nereden başlamak lazım?`];if(st.intent==='question')a=[`Güzel soru; ben de burayı anlamaya çalışıyorum. Siz ne önerirsiniz?`,`Ben de emin değilim; birlikte en mantıklı seçeneği bulalım mı?`,`Aslında tam onu merak ediyordum; sizin ilk izleniminiz ne?`];if(st.intent==='end')a=[`Öneriniz için teşekkür ederim; rahatsız etmeyeyim, iyi vakitler.`,`Çok teşekkürler, yeterince fikir verdi. Size iyi akşamlar.`,`Sağ olun, kısa tuttum. Keyfinizi bölmeyeyim.`];return a}
function answer(mode){if(!st.sel)return;let a=lines();if(mode==='short')a=a.map(x=>x.replace('Merhaba, ','').replace('kısa bir şey sorabilir miyim; ','').replace('burayı çok iyi bilmiyorum; ',''));if(mode==='warm')a=a.map(x=>x.replace('Merhaba,','Merhaba, rahatsız etmiyorsam').replace('Selam,','Selam, rahatsız etmiyorsam'));if(mode==='direct')a=a.map(x=>x.replace('Merhaba, ','').replace('rahatsız etmiyorsam ','').replace('kısa bir şey sorabilir miyim; ',''));if(mode==='next')st.idx=(st.idx+1)%a.length;else st.idx=0;const line=a[st.idx%a.length];ui.answer.innerHTML=`<h2>Şimdi söyle</h2><div class='say'>“${esc(line)}”</div><div class='why'><b>Neden:</b> Mekân veya seçilen duruma bağlı, düşük baskılı ve cevaplaması kolay bir başlangıç. Bilmediği şeyi biliyormuş gibi iddia etmez.</div><div class='actions'><button data-mode='short'>Daha kısa</button><button data-mode='warm'>Daha sıcak</button><button data-mode='direct'>Daha doğrudan</button><button data-mode='next'>Başka öneri</button></div>`;ui.answer.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>answer(b.dataset.mode))}
ui.q.oninput=()=>{clearTimeout(st.timer);st.expanded=false;const v=ui.q.value.trim();if(!v){ui.results.innerHTML='';status('Hazır. Mekânı yazın veya konumunuzu kullanın.');return}st.timer=setTimeout(()=>search(v),430)};
ui.clear.onclick=()=>{ui.q.value='';ui.results.innerHTML='';status('Hazır. Mekânı yazın veya konumunuzu kullanın.');ui.q.focus()};ui.loc.onclick=useLocation;ui.voice.onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast('Bu tarayıcıda sesli giriş desteklenmiyor.');return}const r=new SR();r.lang='tr-TR';r.interimResults=false;r.onresult=e=>{ui.q.value=e.results[0][0].transcript;search(ui.q.value)};r.onerror=()=>toast('Ses alınamadı.');r.start()};ui.startTab.onclick=()=>document.getElementById('start').scrollIntoView({behavior:'smooth'});ui.rescueTab.onclick=()=>{if(!st.sel){st.sel={name:'bu ortam',address:'Hızlı kurtarma',source:'Kullanıcı girişi',type:'unknown'};ui.selected.classList.add('hidden');ui.intent.classList.remove('hidden');ui.answer.classList.remove('hidden')}st.intent='silence';renderIntent();answer();ui.intent.scrollIntoView({behavior:'smooth'})};ui.privacyTab.onclick=()=>{ui.privacy.classList.toggle('hidden');ui.privacy.scrollIntoView({behavior:'smooth'})};window.addEventListener('online',()=>ui.net.textContent='Çevrimiçi');window.addEventListener('offline',()=>ui.net.textContent='Çevrimdışı');loadLoc();console.info('FirstStep QA 2.1.0',{nearLimitMeters:500,typo:'roaster≈rooster',salonType:true});
})();