(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const q = $('q'), results = $('results'), status = $('status'), selectedCard = $('selectedCard'), intentCard = $('intentCard'), answerCard = $('answerCard'), intentChips = $('intentChips'), toast = $('toast');
  const locBtn = $('locBtn'), voiceBtn = $('voiceBtn'), net = $('net');
  const state = { selected:null, intent:'approach', lastLocation:null, used:new Set(), altIndex:0, searchTimer:null, abort:null };
  const intents = [['approach','Birine yaklaş'], ['silence','Sessizlik oldu'], ['group','Gruba katıl'], ['question','Bana soru sordu'], ['end','Kibarca bitir']];
  const osmKinds = {bar:'Bar', pub:'Pub', cafe:'Kafe', restaurant:'Restoran', fast_food:'Hızlı yemek', food_court:'Yemek alanı', nightclub:'Gece mekânı', hotel:'Otel', beach:'Plaj', beach_resort:'Plaj / resort', park:'Park', mall:'AVM', marketplace:'Pazar', cinema:'Sinema', theatre:'Tiyatro', attraction:'Turistik yer', museum:'Müze', ferry_terminal:'Ulaşım', bus_station:'Ulaşım', station:'Ulaşım'};
  const kindMap = {bar:'bar', pub:'bar', nightclub:'bar', cafe:'cafe', restaurant:'restaurant', fast_food:'restaurant', food_court:'restaurant', hotel:'hotel', beach:'beach', beach_resort:'beach', park:'park', mall:'mall', marketplace:'market', cinema:'event', theatre:'event', attraction:'place', museum:'place', ferry_terminal:'transport', bus_station:'transport', station:'transport'};
  const bank = {
    bar: {approach:['Merhaba, menüde karar vermekte zorlandım. Burada gerçekten iyi olan bir şey var mı?','Merhaba, kısa bir şey sorabilir miyim? Burada en çok ne tavsiye edilir?','Merhaba, buranın atmosferi güzel görünüyor. Burada denenmesi gereken bir şey var mı?','Merhaba, rahatsız etmeyeceksem bir öneri alabilir miyim? Burada ne sipariş etmek mantıklı?'],silence:['Sessizlik oldu ama sorun değil. Siz buraya daha çok ortam için mi, menü için mi geliyorsunuz?','Konuyu zorlamadan sorayım: burada sizi en çok ne tuttu, müzik mi ortam mı?'],group:['Merhaba, bölmeyeceğim; burası için bir öneri sorabilir miyim? Masada en çok ne beğenildi?'],question:['Güzel soru. Ben de burayı anlamaya çalışıyorum; sizce buranın en iyi tarafı ne?'],end:['Sizi daha fazla bölmeyeyim. Tavsiye için teşekkür ederim, iyi akşamlar.']},
    restaurant: {approach:['Merhaba, menüde kararsız kaldım. Burada gerçekten tavsiye edeceğiniz bir şey var mı?','Merhaba, kısa bir öneri sorabilir miyim? Burada hangi yemek güvenli tercih olur?','Merhaba, buranın iyi bilinen bir yemeği var mı? İlk bakışta karar veremedim.','Merhaba, sizce burada tatlı mı ana yemek mi daha güçlü?'],silence:['Bu arada menüde sizi şaşırtan iyi bir şey oldu mu?','Konuyu yormadan sorayım: burada tekrar sipariş ederim dediğiniz bir şey var mı?'],group:['Merhaba, masanızı bölmek istemem; burada en çok tavsiye edeceğiniz şey ne olur?'],question:['Ben sade ve iyi bir tercih arıyorum. Siz neyi önerirdiniz?'],end:['Tavsiye için teşekkür ederim. Afiyet olsun, sizi bölmeyeyim.']},
    cafe: {approach:['Merhaba, kahve konusunda kararsız kaldım. Burada gerçekten iyi olan hangisi?','Merhaba, burada çalışmak/oturmak için en iyi köşe neresi sizce?','Merhaba, kısa bir öneri sorabilir miyim? Burada kahve mi tatlı mı daha iyi?','Merhaba, buranın sakin kalacak bir saati var mı biliyor musunuz?'],silence:['Bu arada burası çalışmak için mi daha iyi, sohbet için mi?','Kahve iyi çıktı mı? Ben de ne alacağıma karar veremedim.'],group:['Merhaba, sizi bölmeyeceğim; burada tatlı veya kahve için net bir öneriniz var mı?'],question:['Ben de kahve tarafına bakıyordum. Burada neyi seçmek mantıklı sizce?'],end:['Teşekkür ederim, sizi rahatsız etmeyeyim. İyi günler.']},
    beach: {approach:['Merhaba, kısa bir şey sorabilir miyim? Burada oturmak için en iyi taraf neresi?','Merhaba, buranın deniz/rüzgâr durumu için dikkat edilmesi gereken bir tarafı var mı?','Merhaba, burayı bilen biri gibi görünüyorsunuz; gün batımı için hangi taraf daha iyi?','Merhaba, buraya ilk kez gelmiş gibi davranmadan sorayım: burada en rahat nokta neresi?'],silence:['Burası bugün kalabalığa rağmen iyi görünüyor. Sizce en iyi saat ne zaman?','Bu tarafta rüzgâr hep böyle mi oluyor, biliyor musunuz?'],group:['Merhaba, bölmeyeceğim; burada oturmak için en iyi tarafı sorabilir miyim?'],question:['Ben de ortamı çözmeye çalışıyorum. Size göre burada en iyi nokta neresi?'],end:['Teşekkür ederim, iyi vakitler.']},
    hotel: {approach:['Merhaba, buradaki bar/restoran için kısa bir öneri sorabilir miyim? En güvenli tercih nedir?','Merhaba, bu otelde ilk dikkat edilmesi gereken iyi bir yer var mı?','Merhaba, rahatsız etmeyeceksem sorayım: burada en iyi oturma alanı neresi?'],silence:['Otel içinde en iyi yer burası mı sizce, yoksa başka bir alan var mı?'],group:['Merhaba, sizi bölmeyeceğim; burada kısa bir öneri alabilir miyim?'],question:['Ben de yeri yeni çözüyorum. Sizce burada en mantıklı tercih ne?'],end:['Teşekkür ederim, iyi akşamlar.']},
    mall: {approach:['Merhaba, kısa bir şey sorabilir miyim? Burada yemek/kahve için en mantıklı yer neresi?','Merhaba, bu AVM’de gerçekten tavsiye edeceğiniz bir yer var mı?','Merhaba, burada kalabalığa değen bir yer arıyorum. Bir öneriniz olur mu?'],silence:['Burada seçenek çok ama karar zor. Sizce en iyi taraf neresi?'],group:['Merhaba, bölmeyeceğim; burada hızlıca ne önerirsiniz?'],question:['Ben de seçenekleri azaltmaya çalışıyorum. Siz nereden başlardınız?'],end:['Teşekkür ederim, kolay gelsin.']},
    transport: {approach:['Merhaba, yanlış yerde beklemeyeyim: bu sıra/alan doğru mu biliyor musunuz?','Merhaba, kısa bir şey sorabilir miyim? Buradan devam etmek doğru mu?','Merhaba, burada yönlendirme biraz karışık geldi. Siz de aynı yöne mi gidiyorsunuz?'],silence:['Beklemek bazen en zor kısım. Burası genelde böyle mi oluyor?'],group:['Merhaba, sizi bölmeyeyim; bu yön/sıra doğru mu acaba?'],question:['Ben de kontrol ediyorum. En iyisi tabelaya göre teyit etmek gibi görünüyor.'],end:['Teşekkür ederim, iyi yolculuklar.']},
    generic: {approach:['Merhaba, kısa bir şey sorabilir miyim? Burada dikkat etmeye değer bir şey var mı?','Merhaba, burayı yeni anlamaya çalışıyorum. Burada neye bakmak mantıklı?','Merhaba, rahatsız etmeyeceksem bu yer hakkında küçük bir öneri alabilir miyim?','Merhaba, burada karar vermekte zorlandım. Sizce nereden başlamak mantıklı?'],silence:['Konuyu zorlamadan sorayım: burası sizce ne için daha iyi?','Burası beklediğiniz gibi çıktı mı?'],group:['Merhaba, sizi bölmeyeceğim; bu yer hakkında kısa bir öneri alabilir miyim?'],question:['Ben de yeri yeni çözüyorum. Siz ne önerirsiniz?'],end:['Teşekkür ederim, iyi günler.']}
  };
  function esc(s){return String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function show(el){el.classList.remove('hidden')} function hide(el){el.classList.add('hidden')}
  function setStatus(text, type=''){ status.textContent=text; status.className='status '+type; show(status); }
  function clearStatus(){ hide(status); status.textContent=''; }
  function notify(t){ toast.textContent=t; toast.classList.add('show'); setTimeout(()=>toast.classList.remove('show'),2600); }
  function online(){ net.textContent=navigator.onLine?'Çevrimiçi':'Çevrimdışı'; }
  window.addEventListener('online',online); window.addEventListener('offline',online); online();
  function addressLine(p){ const a=p.address||{}; return [a.road,a.neighbourhood||a.suburb,a.city||a.town||a.village||a.county,a.state,a.country].filter(Boolean).slice(0,5).join(', ') || p.display_name || ''; }
  function detectKind(p){ const ex=p.extratags||{}, cls=p.class||'', typ=p.type||''; const vals=[typ, cls, ex.amenity, ex.tourism, ex.leisure, ex.shop, ex.natural].filter(Boolean).map(x=>String(x).toLowerCase()); for(const v of vals){ if(kindMap[v]) return kindMap[v]; } if(vals.includes('beach')) return 'beach'; if(cls==='place' || typ==='city' || typ==='town' || typ==='village') return 'place'; return 'generic'; }
  function labelKind(p){ const ex=p.extratags||{}, raw=ex.amenity||ex.tourism||ex.leisure||ex.shop||ex.natural||p.type||p.class||'place'; return osmKinds[String(raw).toLowerCase()] || String(raw).replace(/_/g,' '); }
  function nameOf(p){return p.namedetails?.name || p.name || p.display_name?.split(',')[0] || q.value.trim() || 'Seçilen yer';}
  function normalisePlace(p, source='Açık mekân verisi'){ return { name:nameOf(p), address:addressLine(p), lat:Number(p.lat), lon:Number(p.lon), kind:detectKind(p), kindLabel:labelKind(p), source, raw:p, confidence:detectKind(p)==='place'?'Orta':'Orta' }; }
  function overpassPlace(el){ const tags=el.tags||{}, raw=tags.amenity||tags.tourism||tags.leisure||tags.shop||tags.natural||'place'; const p={name:tags.name||'Yakındaki yer', lat:el.lat||el.center?.lat, lon:el.lon||el.center?.lon, class:'amenity', type:raw, extratags:tags, address:{}}; return { name:p.name, address:[tags['addr:street'], tags['addr:city'], tags['addr:country']].filter(Boolean).join(', ') || 'Yakınınızda', lat:p.lat, lon:p.lon, kind:detectKind(p), kindLabel:labelKind(p), source:'Yakındaki açık mekân verisi', raw:p, confidence:'Orta' }; }
  async function nominatimSearch(text, signal){ const url = 'https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&extratags=1&namedetails=1&limit=8&q=' + encodeURIComponent(text); const r = await fetch(url, {signal, headers:{'Accept':'application/json'}}); if(!r.ok) throw new Error('search'); return await r.json(); }
  async function reverse(lat,lon){ const url='https://nominatim.openstreetmap.org/reverse?format=jsonv2&addressdetails=1&extratags=1&namedetails=1&lat='+lat+'&lon='+lon; const r=await fetch(url,{headers:{'Accept':'application/json'}}); if(!r.ok) throw new Error('reverse'); return await r.json(); }
  async function nearby(lat,lon){ const query=`[out:json][timeout:12];(node(around:450,${lat},${lon})[amenity~"restaurant|cafe|bar|pub|fast_food|food_court|nightclub"];way(around:450,${lat},${lon})[amenity~"restaurant|cafe|bar|pub|fast_food|food_court|nightclub"];node(around:450,${lat},${lon})[tourism~"hotel|attraction|museum"];way(around:450,${lat},${lon})[tourism~"hotel|attraction|museum"];node(around:450,${lat},${lon})[leisure~"park|beach_resort"];way(around:450,${lat},${lon})[leisure~"park|beach_resort"];node(around:450,${lat},${lon})[shop~"mall|marketplace"];way(around:450,${lat},${lon})[shop~"mall|marketplace"];);out center tags 15;`; const r=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',body:'data='+encodeURIComponent(query),headers:{'Content-Type':'application/x-www-form-urlencoded'}}); if(!r.ok) throw new Error('overpass'); const j=await r.json(); return (j.elements||[]).filter(e=>e.tags&&e.tags.name).slice(0,10).map(overpassPlace); }
  function renderResults(items, note){ results.innerHTML=''; if(note){ setStatus(note, 'warn'); } if(!items.length){ hide(results); return; } items.forEach((item)=>{ const b=document.createElement('button'); b.className='result'; b.type='button'; b.setAttribute('role','option'); b.innerHTML=`<strong>${esc(item.name)}</strong><small>${esc(item.address)}</small><span class="tag">${esc(item.kindLabel)} · ${esc(item.source)}</span>`; b.addEventListener('click',()=>selectVenue(item)); results.appendChild(b); }); show(results); }
  async function runSearch(text){ const s=text.trim(); if(s.length<3){ hide(results); clearStatus(); return; } if(state.abort) state.abort.abort(); state.abort=new AbortController(); setStatus('Açık mekân verisinde aranıyor…'); try{ let query=s; if(state.lastLocation && !/\b(oman|indonesia|turkey|muscat|denpasar|istanbul|izmir|ankara|bali)\b/i.test(query)) query += ' ' + state.lastLocation.hint; const data=await nominatimSearch(query, state.abort.signal); const items=data.map(x=>normalisePlace(x)).filter(x=>x.name&&x.address); if(items.length){ clearStatus(); renderResults(items); } else { setStatus('Açık veride sonuç bulunamadı. Yazdığınız bilgiyle genel öneri üretilebilir.', 'warn'); renderResults([manualFallback(s)], ''); } }catch(e){ if(e.name==='AbortError')return; setStatus('Arama servisine ulaşılamadı. Yazdığınız bilgiyle devam edebilirsiniz.', 'warn'); renderResults([manualFallback(s)], ''); } }
  function manualFallback(text){ return {name:text, address:state.lastLocation?.hint || 'Manuel giriş', kind:'generic', kindLabel:'Tür bilinmiyor', source:'Manuel giriş', confidence:'Düşük', manual:true}; }
  q.addEventListener('input',()=>{ clearTimeout(state.searchTimer); state.searchTimer=setTimeout(()=>runSearch(q.value),380); });
  q.addEventListener('keydown',(e)=>{ if(e.key==='Enter'){ e.preventDefault(); if(results.querySelector('.result')) results.querySelector('.result').click(); else selectVenue(manualFallback(q.value.trim()||'Bulunduğum yer')); }});
  locBtn.addEventListener('click',()=>{ if(!navigator.geolocation){ setStatus('Bu cihaz/tarayıcı konum özelliği sunmuyor. Mekân adını yazın.', 'bad'); return; } locBtn.disabled=true; setStatus('Konum izni bekleniyor…'); navigator.geolocation.getCurrentPosition(async pos=>{ const {latitude:lat, longitude:lon}=pos.coords; state.lastLocation={lat,lon,hint:`${lat.toFixed(5)}, ${lon.toFixed(5)}`}; setStatus('Konum alındı. Adres ve yakındaki mekânlar aranıyor…','good'); let addrText=state.lastLocation.hint; try{ const rev=await reverse(lat,lon); addrText=addressLine(rev)||addrText; state.lastLocation.hint=addrText; q.value=addrText; }catch(_){ q.value=addrText; } try{ const places=await nearby(lat,lon); if(places.length){ clearStatus(); renderResults(places); } else setStatus('Konum alındı. Yakında açık veriyle listelenmiş mekân bulunamadı. Mekân adını yazın; bu konum içinde arayacağım.','warn'); }catch(_){ setStatus('Konum alındı. Yakındaki mekân listesi alınamadı. Mekân adını yazın; bu konum içinde arayacağım.','warn'); } locBtn.disabled=false; }, err=>{ const msg=err.code===1?'Konum izni verilmedi. Tarayıcı/site izinlerinden konumu açın veya mekân adını yazın.':err.code===2?'Konum alınamadı. GPS/bağlantı kapalı olabilir; mekân adını yazın.':'Konum alma süresi doldu. Mekân adını yazın.'; setStatus(msg,'bad'); locBtn.disabled=false; }, {enableHighAccuracy:true, timeout:12000, maximumAge:60000}); });
  voiceBtn.addEventListener('click',()=>{ const SR=window.SpeechRecognition||window.webkitSpeechRecognition; if(!SR){ notify('Bu tarayıcıda sesli giriş desteklenmiyor. Yazı alanını kullanın.'); return; } const rec=new SR(); rec.lang='tr-TR'; rec.interimResults=false; rec.maxAlternatives=1; setStatus('Dinliyorum… Mekân adı veya şehir söyleyin.'); rec.onresult=e=>{ q.value=e.results[0][0].transcript; runSearch(q.value); }; rec.onerror=()=>setStatus('Ses alınamadı. Yazı alanını kullanın.','warn'); rec.start(); });
  function selectVenue(v){ state.selected=v; state.used.clear(); state.altIndex=0; hide(results); clearStatus(); q.value=v.name; selectedCard.innerHTML=`<div class="venue-title"><div><h2>${esc(v.name)}</h2><p>${esc(v.address||'Konum bilgisi yok')}</p></div><span class="badge">Güven: ${esc(v.confidence)}</span></div><div class="meta"><div><span>Tür</span><b>${esc(v.kindLabel)}</b></div><div><span>Kaynak</span><b>${esc(v.source)}</b></div></div>${v.kind==='generic'||v.kind==='place'?typeFallbackHtml():''}`; show(selectedCard); renderIntents(); makeAnswer(); window.scrollTo({top:selectedCard.offsetTop-10,behavior:'smooth'}); }
  function typeFallbackHtml(){ return `<div class="fallback-type"><p>Tür net değilse tek dokunuşla düzeltin:</p><div class="chips">${[['cafe','Kafe'],['restaurant','Restoran'],['bar','Bar'],['beach','Plaj'],['mall','AVM'],['transport','Ulaşım']].map(([k,l])=>`<button class="pill" data-kind="${k}" type="button">${l}</button>`).join('')}</div></div>`; }
  selectedCard.addEventListener('click',e=>{ const b=e.target.closest('[data-kind]'); if(!b||!state.selected)return; state.selected.kind=b.dataset.kind; state.selected.kindLabel=b.textContent; state.selected.confidence='Orta'; selectVenue(state.selected); });
  function renderIntents(){ intentChips.innerHTML=intents.map(([k,l])=>`<button class="pill ${state.intent===k?'active':''}" data-intent="${k}" type="button">${l}</button>`).join(''); show(intentCard); }
  intentChips.addEventListener('click',e=>{ const b=e.target.closest('[data-intent]'); if(!b)return; state.intent=b.dataset.intent; renderIntents(); makeAnswer(); });
  function linesFor(v,intent){ const k=bank[v.kind]?v.kind:'generic'; return bank[k][intent] || bank[k].approach || bank.generic.approach; }
  function nextLine(){ const v=state.selected||manualFallback(q.value||'Bulunduğum yer'); const arr=linesFor(v,state.intent); let line=arr[state.altIndex%arr.length]; let guard=0; while(state.used.has(line)&&guard<arr.length){ state.altIndex++; line=arr[state.altIndex%arr.length]; guard++; } state.used.add(line); state.altIndex++; if(state.used.size>=arr.length) state.used.clear(); return line; }
  function makeAnswer(style){ if(!state.selected){ selectVenue(manualFallback(q.value.trim()||'Bulunduğum yer')); return; } let line=nextLine(); if(style==='short') line=line.replace('Merhaba, ','').replace('kısa bir şey sorabilir miyim? ','').replace('rahatsız etmeyeceksem ',''); if(style==='warm') line=line.replace('Merhaba,','Merhaba, rahatsız etmeyeceksem'); if(style==='direct') line=line.replace('kısa bir şey sorabilir miyim? ','').replace('rahatsız etmeyeceksem ',''); answerCard.innerHTML=`<h2>Şimdi söyle</h2><div class="say">“${esc(line)}”</div><p class="why"><b>Neden:</b> Mekân/ortam üzerinden düşük baskılı, cevaplaması kolay ve somut bir başlangıç yapar. Bilinmeyen şeyi biliyormuş gibi iddia etmez.</p><div class="answer-actions"><button data-style="short" type="button">Daha kısa</button><button data-style="warm" type="button">Daha sıcak</button><button data-style="direct" type="button">Daha doğrudan</button><button data-style="other" type="button">Başka öneri</button></div><small>Güven: ${esc(state.selected.confidence)} · ${esc(state.selected.source)}</small>`; show(answerCard); }
  answerCard.addEventListener('click',e=>{ const b=e.target.closest('[data-style]'); if(!b)return; makeAnswer(b.dataset.style==='other'?undefined:b.dataset.style); });
  $('tabHome').addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));
  $('tabRescue').addEventListener('click',()=>{ state.intent='silence'; if(!state.selected) selectVenue(manualFallback(q.value.trim()||'Bulunduğum yer')); renderIntents(); makeAnswer(); });
  $('tabPrivacy').addEventListener('click',()=>notify('Konuşma kaydı, hesap ve gizli dinleme yok. Konum yalnızca siz bastığınızda kullanılır.'));
  if('serviceWorker' in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js?v=1.0.0').catch(()=>{}));
})();